#!/usr/bin/env python3
"""Generate the contract and API reference tables for the public docs.

Inputs (the single sources of truth):
  - spec/Contracts/kernel/v1/schemas/*.schema.json   (kernel ABI 1.0.0)
  - surfaces/docs/api/agency/openapi-v0.3.yaml       (Agency API v0.3, public copy)

Outputs (never edit these by hand; rerun this script instead):
  - surfaces/docs/api/agency/schemas.mdx                       (whole page)
  - surfaces/docs/architecture/kernel-contracts-reference.mdx  (whole page)
  - surfaces/docs/api/agency/errors.mdx                        (only the block between
    the GENERATED markers)

Usage (from the repo root or anywhere):
  python3 surfaces/docs/scripts/gen_reference.py          # write files
  python3 surfaces/docs/scripts/gen_reference.py --check  # exit 1 if output is stale

Requires PyYAML. The script is deterministic: running it twice produces no diff.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import yaml

DOCS = Path(__file__).resolve().parent.parent
REPO = DOCS.parent.parent
ABI_DIR = REPO / "spec" / "Contracts" / "kernel" / "v1"
OPENAPI = DOCS / "api" / "agency" / "openapi-v0.3.yaml"

PREVIEW_WARNING = (
    "<Warning>\n"
    "**PREVIEW.** The Agency API is not live yet. This page describes the published v0.3 "
    "contract so you can review and build against it; details may change before alpha. "
    "Implementation status: DESIGN — NOT YET IMPLEMENTED.\n"
    "</Warning>\n"
)
GEN_NOTE = (
    "{/* GENERATED by surfaces/docs/scripts/gen_reference.py. Do not edit by hand. */}\n"
)


def esc(text: str | None) -> str:
    """Make free text safe for one MDX table cell."""
    if not text:
        return ""
    t = " ".join(str(text).split())
    t = t.replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;")
    t = t.replace("{", "&#123;").replace("}", "&#125;")
    return t


def anchor(name: str) -> str:
    return re.sub(r"[^a-z0-9-]", "", name.lower().replace(" ", "-"))


# ---------------------------------------------------------------- type rendering
def type_of(s: dict, link) -> str:
    if not isinstance(s, dict):
        return ""
    if "$ref" in s:
        return link(s["$ref"])
    if "const" in s:
        return f'`{json.dumps(s["const"])}`'
    for key in ("oneOf", "anyOf"):
        if key in s:
            return " \\| ".join(type_of(x, link) for x in s[key])
    if "allOf" in s:
        return " & ".join(type_of(x, link) for x in s["allOf"])
    t = s.get("type")
    types = t if isinstance(t, list) else ([t] if t else [])
    parts = []
    for ty in types:
        if ty == "array":
            parts.append(f"array of {type_of(s.get('items', {}), link) or 'any'}")
        elif ty == "string" and "enum" in s:
            parts.append("enum")
        elif ty == "string" and s.get("format"):
            parts.append(f"string ({s['format']})")
        elif ty == "object" and "additionalProperties" in s and not s.get("properties"):
            ap = s["additionalProperties"]
            parts.append(
                f"map of {type_of(ap, link) or 'any'}" if isinstance(ap, dict) else "object"
            )
        else:
            parts.append(ty)
    if not parts and "enum" in s:
        parts.append("enum")
    if not parts and "properties" in s:
        parts.append("object")
    out = " \\| ".join(parts)
    if "enum" in s:
        vals = ", ".join(f"`{v}`" for v in s["enum"] if v is not None)
        out += f": {vals}"
    return out


def field_rows(schema: dict, link, prefix: str = "") -> list[str]:
    rows = []
    props = schema.get("properties") or {}
    req = set(schema.get("required") or [])
    for name, sub in props.items():
        full = f"{prefix}{name}"
        sub = sub if isinstance(sub, dict) else {}
        tier = sub.get("x-disclosure-tier", "")
        desc = esc(sub.get("description"))
        if tier:
            desc = (f"Disclosure tier {tier}. " + desc).strip()
        rows.append(
            f"| `{full}` | {type_of(sub, link)} | {'yes' if name in req else 'no'} | {desc} |"
        )
        if sub.get("type") == "object" and sub.get("properties"):
            rows += field_rows(sub, link, f"{full}.")
        items = sub.get("items") if isinstance(sub.get("items"), dict) else None
        if items and items.get("properties"):
            rows += field_rows(items, link, f"{full}[].")
    return rows


def render_schema(name: str, s: dict, link, level: str = "##") -> list[str]:
    out = [f"{level} {name}", ""]
    if s.get("description"):
        out += [esc(s["description"]), ""]
    if s.get("properties"):
        out += ["| Field | Type | Required | Description |", "|-------|------|----------|-------------|"]
        out += field_rows(s, link)
        out.append("")
        if s.get("additionalProperties") is False:
            out += ["No other properties are accepted.", ""]
    elif "enum" in s:
        out += ["Type: string enum.", "", "| Value |", "|-------|"]
        out += [f"| `{v}` |" for v in s["enum"]]
        out.append("")
    elif any(k in s for k in ("oneOf", "anyOf", "allOf", "$ref")):
        out += [f"One of: {type_of(s, link)}.", ""]
    elif s.get("type") == "object" and isinstance(s.get("additionalProperties"), dict):
        out += [f"Map of string to {type_of(s['additionalProperties'], link)}.", ""]
    elif s.get("type"):
        out += [f"Type: {type_of(s, link)}.", ""]
    return out


# ---------------------------------------------------------------- Agency API
def gen_agency_schemas(api: dict) -> str:
    schemas = api["components"]["schemas"]

    def link(ref: str) -> str:
        n = ref.rsplit("/", 1)[-1]
        return f"[{n}](#{anchor(n)})"

    lines = [
        "---",
        "title: 'Agency API schemas'",
        "description: 'Every object, enum and field in the Agency API v0.3 contract.'",
        "---",
        "",
        GEN_NOTE,
        PREVIEW_WARNING,
        f"This page lists all {len(schemas)} component schemas in the "
        "[v0.3 OpenAPI contract](/api/agency/openapi), in contract order. The tables are "
        "generated from the contract file by `surfaces/docs/scripts/gen_reference.py`, so they "
        "match it field for field. Nested inline objects are flattened with dotted names "
        "(`data.from`, `criteria[].result`).",
        "",
        "## Reading the tables",
        "",
        "- **Required** means the field must be present: in a request body you must send it, and in a response the server always returns it. A field marked `no` may be absent.",
        "- **Disclosure tier** marks fields outside the everyday surface: B is the capability tier, C is the graph tier, D is the runtime tier. See [progressive disclosure](/api/agency/overview#progressive-disclosure).",
        "- Request objects are closed unless the table says otherwise. Unknown request fields are rejected with `ERR_INPUT_UNSUPPORTED`. Clients must ignore unknown response fields and treat unknown enum values as not understood. See [Versioning](/api/agency/versioning).",
        "- Names ending in `V1` in descriptions (for example `AttentionRequestV1`) refer to [kernel contracts](/architecture/kernel-contracts). The API objects are public views of those contracts.",
        "",
        "## Index",
        "",
        " · ".join(f"[{n}](#{anchor(n)})" for n in schemas),
        "",
    ]
    for name, s in schemas.items():
        lines += render_schema(name, s, link)
    return "\n".join(lines).rstrip() + "\n"


def gen_error_block(api: dict) -> str:
    err = api["components"]["schemas"]["Error"]["properties"]
    families = err["family"]["enum"]
    desc = err["code"]["description"]
    kernel_part, _, api_part = desc.partition("API codes:")
    kernel = re.findall(r"ERR_[A-Z0-9_]+", kernel_part)
    api_codes = re.findall(r"ERR_[A-Z0-9_]+", api_part)
    all_codes = sorted(set(re.findall(r"ERR_[A-Z0-9_]+", yaml.safe_dump(api))))
    responses = api["components"]["responses"]
    lines = [
        GEN_NOTE,
        "### Error families",
        "",
        "| Family | Origin |",
        "|--------|--------|",
    ]
    api_fams = {"AUTH", "NOT_FOUND", "IDEMPOTENCY", "RATE_LIMIT", "VERSION"}
    lines += [f"| `{f}` | {'API surface' if f in api_fams else 'Kernel runtime'} |" for f in families]
    lines += ["", "### Error codes", "", "| Code | Origin |", "|------|--------|"]
    for c in all_codes:
        origin = "Kernel (passed through unchanged)" if c in kernel else (
            "API surface" if c in api_codes else "API surface")
        lines.append(f"| `{c}` | {origin} |")
    lines += ["", "### Standard error responses", "", "| Response | Meaning |", "|----------|---------|"]
    lines += [f"| `{k}` | {esc(v.get('description'))} |" for k, v in responses.items()]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- Kernel ABI
def gen_kernel_reference() -> str:
    manifest = json.loads((ABI_DIR / "MANIFEST.json").read_text())
    version = manifest.get("package_version", "1.0.0")
    files = sorted((ABI_DIR / "schemas").glob("*.schema.json"))

    def link(ref: str) -> str:
        file_part, _, frag = ref.partition("#")
        n = frag.rsplit("/", 1)[-1] if frag else file_part
        return f"[{n}](#{anchor(n)})"

    body, index, count = [], [], 0
    for f in files:
        d = json.loads(f.read_text())
        defs = d.get("$defs", {})
        body += [f"## {f.name}", ""]
        if d.get("title"):
            body += [esc(d["title"]), ""]
        body += [f"Schema `$id`: `{d.get('$id', '')}`", ""]
        for name, s in defs.items():
            count += 1
            index.append(f"[{name}](#{anchor(name)})")
            body += render_schema(name, s, link, "###")
    head = [
        "---",
        "title: 'Kernel contracts reference'",
        f"description: 'Every definition and field in kernel ABI {version}, generated from the schemas.'",
        "---",
        "",
        GEN_NOTE,
        f"**Status: AVAILABLE** (contract package). This page lists all {count} definitions in the "
        f"{len(files)} schema files of kernel ABI {version} under `spec/Contracts/kernel/v1/schemas/`. "
        "It is generated by `surfaces/docs/scripts/gen_reference.py`; the schemas are normative and "
        "this page is a projection of them. A frozen contract is a specification; it does not mean "
        "the component that implements it is built. See [Kernel contracts](/architecture/kernel-contracts).",
        "",
        "## Index",
        "",
        " · ".join(index),
        "",
    ]
    return "\n".join(head + body).rstrip() + "\n"


def splice(path: Path, block: str) -> str:
    text = path.read_text()
    begin, end = "{/* BEGIN GENERATED */}", "{/* END GENERATED */}"
    if begin not in text or end not in text:
        raise SystemExit(f"{path}: missing GENERATED markers")
    pre, _, rest = text.partition(begin)
    _, _, post = rest.partition(end)
    return f"{pre}{begin}\n{block}{end}{post}"


def main() -> int:
    check = "--check" in sys.argv
    api = yaml.safe_load(OPENAPI.read_text())
    targets = {
        DOCS / "api" / "agency" / "schemas.mdx": gen_agency_schemas(api),
        DOCS / "architecture" / "kernel-contracts-reference.mdx": gen_kernel_reference(),
        DOCS / "api" / "agency" / "errors.mdx": splice(
            DOCS / "api" / "agency" / "errors.mdx", gen_error_block(api)
        ),
    }
    stale = []
    for path, content in targets.items():
        if path.exists() and path.read_text() == content:
            continue
        stale.append(path.relative_to(REPO))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    for p in stale:
        print(("stale: " if check else "wrote: ") + str(p))
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())
