#!/usr/bin/env python3
"""Generate the Allternit Factory API reference page from the interface contract.

Input (the single source of truth):
  - docs/specs/allternit-factory/API.md   (the /api/factory + CLI contract)

Output (never edit by hand; rerun this script instead):
  - surfaces/docs/factory/api-reference.mdx

Usage (from the repo root or anywhere):
  python3 surfaces/docs/scripts/gen_factory_api.py          # write the page
  python3 surfaces/docs/scripts/gen_factory_api.py --check  # exit 1 if the page is stale

The contract's own preamble (who builds against it, how to request changes) is
for the build streams, so it is replaced with a reader-facing intro. Everything
from the first `## ` heading on is copied as is. Deterministic: two runs, no diff.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent
REPO = DOCS.parent.parent
SRC = REPO / "docs" / "specs" / "allternit-factory" / "API.md"
OUT = DOCS / "factory" / "api-reference.mdx"

HEADER = """---
title: "Factory API reference"
description: "The /api/factory routes and the engine CLI contract: processes, exit codes, resources and shapes."
---

{/* GENERATED by surfaces/docs/scripts/gen_factory_api.py from docs/specs/allternit-factory/API.md. Do not edit by hand. */}

<Note>
This is the v0 interface contract the engine, Gizzi, allternit-api and the apps are built against.
</Note>

The engine serves these routes at `/api/factory`. allternit-api proxies them for Desktop, ai.allternit.com and m.allternit.com, and owns the approvals routes itself. allternit-api also serves the work-engine routes (mail, peers, steer, ledger, plans, leases, gate, vault and more) at `/api/factory` in process; they're listed in [Architecture](/factory/architecture#routes-allternit-api-serves-in-process). See [Architecture](/factory/architecture) for how the pieces fit, and the [command reference](/factory/commands) for the CLI side.

"""


def render() -> str:
    text = SRC.read_text()
    start = text.find("\n## ")
    if start < 0:
        raise SystemExit(f"{SRC}: no '## ' heading found")
    body = text[start + 1 :]
    # Build-stream pointers mean nothing to a reader.
    body = re.sub(r"\s*\(see stream F\d+\)", "", body)
    return HEADER + body.rstrip() + "\n"


def main() -> int:
    if not SRC.is_file():
        print(f"missing source: {SRC}")
        return 1
    out = render()
    if "--check" in sys.argv[1:]:
        if not OUT.is_file() or OUT.read_text() != out:
            print(f"stale: {OUT.relative_to(REPO)} (rerun scripts/gen_factory_api.py)")
            return 1
        print("factory api reference: up to date")
        return 0
    OUT.write_text(out)
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
