// Generated by contracts/computer-toolset/generate.mjs from contracts/computer-toolset/*.json. Do not edit.
/* eslint-disable */

// ---- allternit.computer.v1 (computer_toolset_20260801) ----
export const COMPUTER_MEMBER_NAMES = ["screenshot","zoom","left_click","right_click","middle_click","double_click","triple_click","mouse_move","left_click_drag","left_mouse_down","left_mouse_up","scroll","type","key","hold_key","wait","cursor_position"] as const;
export type ComputerMemberName = (typeof COMPUTER_MEMBER_NAMES)[number];
/** Take a screenshot of the screen. */
export type ComputerScreenshotInput = Record<string, never>;
/** Take a screenshot of a rectangular region. Region coordinates are in the full-screenshot space (not physical display pixels). The crop is scaled up to fill the image budget so fine details become legible. */
export type ComputerZoomInput = { region: Array<number> };
/** Click the left mouse button at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted. */
export type ComputerLeftClickInput = { coordinate?: Array<number> | null; text?: string | null };
/** Click the right mouse button at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted. */
export type ComputerRightClickInput = { coordinate?: Array<number> | null; text?: string | null };
/** Click the middle mouse button at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted. */
export type ComputerMiddleClickInput = { coordinate?: Array<number> | null; text?: string | null };
/** Double-click the left mouse button at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted. */
export type ComputerDoubleClickInput = { coordinate?: Array<number> | null; text?: string | null };
/** Triple-click the left mouse button at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted. */
export type ComputerTripleClickInput = { coordinate?: Array<number> | null; text?: string | null };
/** Move the cursor to a specified (x, y) pixel coordinate. Use this ONLY to hover without clicking; otherwise use a click action directly. */
export type ComputerMouseMoveInput = { coordinate: Array<number> };
/** Click and drag the cursor from `start_coordinate` to `coordinate`. */
export type ComputerLeftClickDragInput = { coordinate: Array<number>; start_coordinate: Array<number>; text?: string | null };
/** Press and hold the left mouse button at the current cursor position. */
export type ComputerLeftMouseDownInput = Record<string, never>;
/** Release the left mouse button. */
export type ComputerLeftMouseUpInput = Record<string, never>;
/** Scroll the screen at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted. Do NOT use PageUp/PageDown to scroll. */
export type ComputerScrollInput = { scroll_amount: number; scroll_direction: "up" | "down" | "left" | "right"; coordinate?: Array<number> | null; text?: string | null };
/** Type a string of text on the keyboard. */
export type ComputerTypeInput = { text: string };
/** Press a key or key-combination on the keyboard. Use "+" to combine modifiers with a key (e.g. "ctrl+s", "alt+Tab", "ctrl+shift+Escape"). Key names are case-insensitive; common names like "Return", "Tab", "Escape", "Up", "Down", "Left", "Right", "Home", "End", "Page_Up", "Page_Down", "Delete", "BackSpace" are supported. */
export type ComputerKeyInput = { text: string; repeat?: number | null };
/** Hold down a key or key-combination for a specified duration. Uses the same key syntax as `key`. */
export type ComputerHoldKeyInput = { duration: number; text: string };
/** Wait for a specified duration. */
export type ComputerWaitInput = { duration: number };
/** Get the current (x, y) pixel coordinate of the cursor. */
export type ComputerCursorPositionInput = Record<string, never>;
export interface ComputerMemberInputs {
  screenshot: ComputerScreenshotInput;
  zoom: ComputerZoomInput;
  left_click: ComputerLeftClickInput;
  right_click: ComputerRightClickInput;
  middle_click: ComputerMiddleClickInput;
  double_click: ComputerDoubleClickInput;
  triple_click: ComputerTripleClickInput;
  mouse_move: ComputerMouseMoveInput;
  left_click_drag: ComputerLeftClickDragInput;
  left_mouse_down: ComputerLeftMouseDownInput;
  left_mouse_up: ComputerLeftMouseUpInput;
  scroll: ComputerScrollInput;
  type: ComputerTypeInput;
  key: ComputerKeyInput;
  hold_key: ComputerHoldKeyInput;
  wait: ComputerWaitInput;
  cursor_position: ComputerCursorPositionInput;
}
export const COMPUTER_CONTRACT = {
  "id": "allternit.computer.v1",
  "toolset": "computer",
  "version": 1,
  "upstream": {
    "anthropic_type": "computer_toolset_20260801",
    "toolset_name": "computer",
    "sdk": "@anthropic-ai/sdk",
    "sdk_version": "0.132.0"
  },
  "batch_halt_text": "Not executed: an earlier computer action in this turn failed.",
  "model_frame": {
    "max_long_edge": 1568,
    "max_pixels": 1150000,
    "rule": "Screenshots are downscaled (never upscaled) to fit long edge <= max_long_edge and width*height <= max_pixels, keeping aspect. Coordinates the model sends are in that frame; the executor scales them to screen pixels. The executor is the only place scaling happens."
  },
  "coordinate_spaces": {
    "pixels": "Model-frame pixels (default).",
    "normalized_1000": "A 0..1000 grid over the screen on both axes (UI-TARS / Qwen-VL style); x_screen = round(x / 1000 * screen_width)."
  },
  "risk_classes": {
    "reversible": "aci_safety::ConfirmationClass::Reversible",
    "risky": "aci_safety::ConfirmationClass::Risky",
    "irreversible": "aci_safety::ConfirmationClass::Irreversible"
  },
  "confirm_rules": {
    "never": "No human approval.",
    "non_sandbox": "Needs a single-use action-hash approval grant on non-sandbox targets (this-device, paired computers). Sandboxed targets (cloud/bot computers, gateway browser sessions) run it without approval.",
    "always": "Always needs a single-use action-hash approval grant.",
    "irreversible": "Any member whose risk is irreversible needs a grant, whatever its confirm rule."
  },
  "result_shape": {
    "type": "object",
    "required": [
      "is_error",
      "content",
      "screen"
    ],
    "properties": {
      "is_error": {
        "type": "boolean"
      },
      "content": {
        "type": "array",
        "items": {
          "anyOf": [
            {
              "type": "object",
              "required": [
                "type",
                "text"
              ],
              "properties": {
                "type": {
                  "const": "text"
                },
                "text": {
                  "type": "string"
                }
              }
            },
            {
              "type": "object",
              "required": [
                "type",
                "media_type",
                "data"
              ],
              "properties": {
                "type": {
                  "const": "image"
                },
                "media_type": {
                  "type": "string"
                },
                "data": {
                  "type": "string",
                  "description": "base64, no data: prefix"
                }
              }
            }
          ]
        }
      },
      "screen": {
        "type": "object",
        "required": [
          "width",
          "height",
          "scale"
        ],
        "properties": {
          "width": {
            "type": "integer",
            "description": "screen (or viewport) width in px"
          },
          "height": {
            "type": "integer"
          },
          "scale": {
            "type": "number",
            "description": "screen px per model-frame px (>= 1)"
          },
          "frame_width": {
            "type": "integer"
          },
          "frame_height": {
            "type": "integer"
          }
        }
      }
    }
  },
  "members": [
    {
      "name": "screenshot",
      "description": "Take a screenshot of the screen.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "screenshot",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "zoom",
      "description": "Take a screenshot of a rectangular region. Region coordinates are in the full-screenshot space (not physical display pixels). The crop is scaled up to fill the image budget so fine details become legible.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "screenshot",
      "scale_fields": {
        "region": "rect"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "region": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 4,
            "maxItems": 4,
            "description": "(x0, y0, x1, y1): The region to capture."
          }
        },
        "required": [
          "region"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "left_click",
      "description": "Click the left mouse button at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Clicked.",
      "scale_fields": {
        "coordinate": "point"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "coordinate": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2,
            "description": "(x, y): x pixels from the left edge, y pixels from the top edge."
          },
          "text": {
            "type": "string",
            "description": "Optional key combination to hold down during this action (e.g. \"ctrl\", \"shift\", \"ctrl+shift\")."
          }
        },
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "right_click",
      "description": "Click the right mouse button at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Right-clicked.",
      "scale_fields": {
        "coordinate": "point"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "coordinate": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2,
            "description": "(x, y): x pixels from the left edge, y pixels from the top edge."
          },
          "text": {
            "type": "string",
            "description": "Optional key combination to hold down during this action (e.g. \"ctrl\", \"shift\", \"ctrl+shift\")."
          }
        },
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "middle_click",
      "description": "Click the middle mouse button at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Middle-clicked.",
      "scale_fields": {
        "coordinate": "point"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "coordinate": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2,
            "description": "(x, y): x pixels from the left edge, y pixels from the top edge."
          },
          "text": {
            "type": "string",
            "description": "Optional key combination to hold down during this action (e.g. \"ctrl\", \"shift\", \"ctrl+shift\")."
          }
        },
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "double_click",
      "description": "Double-click the left mouse button at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Double-clicked.",
      "scale_fields": {
        "coordinate": "point"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "coordinate": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2,
            "description": "(x, y): x pixels from the left edge, y pixels from the top edge."
          },
          "text": {
            "type": "string",
            "description": "Optional key combination to hold down during this action (e.g. \"ctrl\", \"shift\", \"ctrl+shift\")."
          }
        },
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "triple_click",
      "description": "Triple-click the left mouse button at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Triple-clicked.",
      "scale_fields": {
        "coordinate": "point"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "coordinate": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2,
            "description": "(x, y): x pixels from the left edge, y pixels from the top edge."
          },
          "text": {
            "type": "string",
            "description": "Optional key combination to hold down during this action (e.g. \"ctrl\", \"shift\", \"ctrl+shift\")."
          }
        },
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "mouse_move",
      "description": "Move the cursor to a specified (x, y) pixel coordinate. Use this ONLY to hover without clicking; otherwise use a click action directly.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Moved the mouse.",
      "scale_fields": {
        "coordinate": "point"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "coordinate": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2,
            "description": "(x, y): x pixels from the left edge, y pixels from the top edge."
          }
        },
        "required": [
          "coordinate"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "left_click_drag",
      "description": "Click and drag the cursor from `start_coordinate` to `coordinate`.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Dragged.",
      "scale_fields": {
        "start_coordinate": "point",
        "coordinate": "point"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "coordinate": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2,
            "description": "(x, y): x pixels from the left edge, y pixels from the top edge."
          },
          "start_coordinate": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2,
            "description": "(x, y): x pixels from the left edge, y pixels from the top edge."
          },
          "text": {
            "type": "string",
            "description": "Optional key combination to hold down during this action (e.g. \"ctrl\", \"shift\", \"ctrl+shift\")."
          }
        },
        "required": [
          "coordinate",
          "start_coordinate"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "left_mouse_down",
      "description": "Press and hold the left mouse button at the current cursor position.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Left mouse button pressed.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "left_mouse_up",
      "description": "Release the left mouse button.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Left mouse button released.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "scroll",
      "description": "Scroll the screen at the specified (x, y) pixel coordinate, or the current cursor position if `coordinate` is omitted. Do NOT use PageUp/PageDown to scroll.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Scrolled {scroll_direction}.",
      "scale_fields": {
        "coordinate": "point"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "scroll_amount": {
            "type": "number",
            "description": "Number of 'clicks' of the scroll wheel."
          },
          "scroll_direction": {
            "type": "string",
            "enum": [
              "up",
              "down",
              "left",
              "right"
            ]
          },
          "coordinate": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2,
            "description": "(x, y): x pixels from the left edge, y pixels from the top edge."
          },
          "text": {
            "type": "string",
            "description": "Optional key combination to hold down during this action (e.g. \"ctrl\", \"shift\", \"ctrl+shift\")."
          }
        },
        "required": [
          "scroll_amount",
          "scroll_direction"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "type",
      "description": "Type a string of text on the keyboard.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": true,
      "confirm": "non_sandbox",
      "result_kind": "none",
      "ack_text": "Typed.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "description": "The text to type."
          }
        },
        "required": [
          "text"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "key",
      "description": "Press a key or key-combination on the keyboard. Use \"+\" to combine modifiers with a key (e.g. \"ctrl+s\", \"alt+Tab\", \"ctrl+shift+Escape\"). Key names are case-insensitive; common names like \"Return\", \"Tab\", \"Escape\", \"Up\", \"Down\", \"Left\", \"Right\", \"Home\", \"End\", \"Page_Up\", \"Page_Down\", \"Delete\", \"BackSpace\" are supported.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": true,
      "confirm": "non_sandbox",
      "result_kind": "none",
      "ack_text": "Pressed {text}.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "description": "The key or key-combination to press."
          },
          "repeat": {
            "type": "number",
            "description": "Number of times to repeat the key press. Default is 1."
          }
        },
        "required": [
          "text"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "hold_key",
      "description": "Hold down a key or key-combination for a specified duration. Uses the same key syntax as `key`.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": true,
      "confirm": "non_sandbox",
      "result_kind": "none",
      "ack_text": "Held {text} for {duration}s.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "duration": {
            "type": "number",
            "description": "Duration to hold the key, in seconds."
          },
          "text": {
            "type": "string",
            "description": "The key or key-combination to hold."
          }
        },
        "required": [
          "duration",
          "text"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "wait",
      "description": "Wait for a specified duration.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Waited {duration}s.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "duration": {
            "type": "number",
            "description": "Duration to wait, in seconds."
          }
        },
        "required": [
          "duration"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "cursor_position",
      "description": "Get the current (x, y) pixel coordinate of the cursor.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "point",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      }
    }
  ]
} as const;

// ---- allternit.browser.v1 (browser_toolset_20260801) ----
export const BROWSER_MEMBER_NAMES = ["navigate","screenshot","zoom","left_click","right_click","middle_click","double_click","triple_click","hover","left_click_drag","left_mouse_down","left_mouse_up","mouse_move","scroll","scroll_to","type","key","hold_key","wait","read_page","find","get_page_text","form_input","file_upload","read_console","read_network","javascript_exec","new_tab","list_tabs","switch_tab","close_tab"] as const;
export type BrowserMemberName = (typeof BROWSER_MEMBER_NAMES)[number];
/** Navigate to a URL, or go back/forward/reload in history. The protocol may be omitted (defaults to https://). */
export type BrowserNavigateInput = { url: string; tab_id?: string | null };
/** Capture the current browser viewport. */
export type BrowserScreenshotInput = { tab_id?: string | null };
/** Return a cropped screenshot of the given viewport region, scaled up for closer inspection — useful for small icons, buttons, or text. Coordinates are in the same viewport-pixel space as a full screenshot. */
export type BrowserZoomInput = { region: Array<number>; tab_id?: string | null };
/** Left-click at a viewport coordinate or on an element by reference. */
export type BrowserLeftClickInput = { target: { type: "coordinate"; x: number; y: number } | { ref: string; type: "ref" }; modifiers?: string | null; tab_id?: string | null };
/** Right-click at a viewport coordinate or on an element by reference. */
export type BrowserRightClickInput = { target: { type: "coordinate"; x: number; y: number } | { ref: string; type: "ref" }; modifiers?: string | null; tab_id?: string | null };
/** Middle-click at a viewport coordinate or on an element by reference. */
export type BrowserMiddleClickInput = { target: { type: "coordinate"; x: number; y: number } | { ref: string; type: "ref" }; modifiers?: string | null; tab_id?: string | null };
/** Double left-click at a viewport coordinate or on an element by reference. */
export type BrowserDoubleClickInput = { target: { type: "coordinate"; x: number; y: number } | { ref: string; type: "ref" }; modifiers?: string | null; tab_id?: string | null };
/** Triple left-click at a viewport coordinate or on an element by reference (typically selects a line or paragraph). */
export type BrowserTripleClickInput = { target: { type: "coordinate"; x: number; y: number } | { ref: string; type: "ref" }; modifiers?: string | null; tab_id?: string | null };
/** Move the cursor to a coordinate or element without clicking. */
export type BrowserHoverInput = { target: { type: "coordinate"; x: number; y: number } | { ref: string; type: "ref" }; tab_id?: string | null };
/** Press at `from`, drag to `target`, release. Both must be coordinate targets. */
export type BrowserLeftClickDragInput = { from: { type: "coordinate"; x: number; y: number }; target: { type: "coordinate"; x: number; y: number }; tab_id?: string | null };
/** Press and hold the left mouse button at a viewport coordinate. Pair with left_mouse_up to perform a custom drag. */
export type BrowserLeftMouseDownInput = { target: { type: "coordinate"; x: number; y: number }; tab_id?: string | null };
/** Release the left mouse button at a viewport coordinate. */
export type BrowserLeftMouseUpInput = { target: { type: "coordinate"; x: number; y: number }; tab_id?: string | null };
/** Move the pointer to a viewport coordinate without clicking. */
export type BrowserMouseMoveInput = { target: { type: "coordinate"; x: number; y: number }; tab_id?: string | null };
/** Scroll at a viewport position. `target` must be a coordinate target. */
export type BrowserScrollInput = { scroll_direction: "up" | "down" | "left" | "right"; target: { type: "coordinate"; x: number; y: number }; scroll_amount?: number | null; tab_id?: string | null };
/** Scroll an element into view. */
export type BrowserScrollToInput = { target: { ref: string; type: "ref" }; tab_id?: string | null };
/** Type a literal string at the current focus. */
export type BrowserTypeInput = { text: string; tab_id?: string | null };
/** Press a key or key chord. Use "+" to combine modifiers with a key (e.g. "ctrl+a", "cmd+shift+p") and space to sequence presses (e.g. "Backspace Backspace Delete"). Common names like "Return", "Tab", "Escape", "BackSpace" are supported. */
export type BrowserKeyInput = { text: string; repeat?: number | null; tab_id?: string | null };
/** Hold a key or key chord down for a duration, then release it. Uses the same key names and "+" chord syntax as the key action. */
export type BrowserHoldKeyInput = { duration: number; text: string; tab_id?: string | null };
/** Pause for the given duration. */
export type BrowserWaitInput = { duration: number; tab_id?: string | null };
/** Return a structured accessibility tree of the page (or the subtree rooted at `ref`), with element references like [ref_7] that can be used as targets on later actions. Output is capped at 50,000 characters — narrow with `ref` or a smaller `depth` when exceeded. */
export type BrowserReadPageInput = { depth?: number | null; filter?: "all" | "interactive" | null; ref?: string | null; tab_id?: string | null };
/** Find elements matching a natural-language description (e.g. "search bar", "add to cart button") and return up to 20 matches with element references. */
export type BrowserFindInput = { query: string; tab_id?: string | null };
/** Return the page's visible text content as plain text, prioritizing article content. Suited to articles, documentation, and other text-heavy pages. */
export type BrowserGetPageTextInput = { tab_id?: string | null };
/** Set the value of a form element (input, textarea, select, checkbox). Use a boolean for checkboxes, an option value or text for selects. */
export type BrowserFormInputInput = { target: { ref: string; type: "ref" }; value: string | number | boolean; tab_id?: string | null };
/** Set the value of a file-input element to one or more files. The target must be an element reference; at least one of paths or document_ids is required. */
export type BrowserFileUploadInput = { target: { ref: string; type: "ref" }; document_ids?: Array<string> | null; paths?: Array<string> | null; tab_id?: string | null };
/** Return console output (log entries, errors, warnings) accumulated since the driver attached to the tab and since the last read, one line per entry. An empty result does not mean no traffic for a tab that predates attach. */
export type BrowserReadConsoleInput = { tab_id?: string | null };
/** Return the network requests (method, URL, status, MIME type, timing) recorded since the driver attached to the tab and since the last read, one line per entry. An empty result does not mean no traffic for a tab that predates attach. */
export type BrowserReadNetworkInput = { tab_id?: string | null };
/** Execute JavaScript in the page context and return the value of the last expression. The code runs with access to the DOM, `window`, and page variables. Write the expression you want evaluated — do NOT use `return`. */
export type BrowserJavascriptExecInput = { text: string; tab_id?: string | null };
/** Open a new empty tab and return its tab_id. */
export type BrowserNewTabInput = Record<string, never>;
/** List all open tabs with each tab's tab_id, title, and URL. */
export type BrowserListTabsInput = Record<string, never>;
/** Make the tab with the given tab_id the active tab — the tab that actions without a tab_id apply to. */
export type BrowserSwitchTabInput = { tab_id: string };
/** Close the tab with the given tab_id. */
export type BrowserCloseTabInput = { tab_id: string };
export interface BrowserMemberInputs {
  navigate: BrowserNavigateInput;
  screenshot: BrowserScreenshotInput;
  zoom: BrowserZoomInput;
  left_click: BrowserLeftClickInput;
  right_click: BrowserRightClickInput;
  middle_click: BrowserMiddleClickInput;
  double_click: BrowserDoubleClickInput;
  triple_click: BrowserTripleClickInput;
  hover: BrowserHoverInput;
  left_click_drag: BrowserLeftClickDragInput;
  left_mouse_down: BrowserLeftMouseDownInput;
  left_mouse_up: BrowserLeftMouseUpInput;
  mouse_move: BrowserMouseMoveInput;
  scroll: BrowserScrollInput;
  scroll_to: BrowserScrollToInput;
  type: BrowserTypeInput;
  key: BrowserKeyInput;
  hold_key: BrowserHoldKeyInput;
  wait: BrowserWaitInput;
  read_page: BrowserReadPageInput;
  find: BrowserFindInput;
  get_page_text: BrowserGetPageTextInput;
  form_input: BrowserFormInputInput;
  file_upload: BrowserFileUploadInput;
  read_console: BrowserReadConsoleInput;
  read_network: BrowserReadNetworkInput;
  javascript_exec: BrowserJavascriptExecInput;
  new_tab: BrowserNewTabInput;
  list_tabs: BrowserListTabsInput;
  switch_tab: BrowserSwitchTabInput;
  close_tab: BrowserCloseTabInput;
}
export const BROWSER_CONTRACT = {
  "id": "allternit.browser.v1",
  "toolset": "browser",
  "version": 1,
  "upstream": {
    "anthropic_type": "browser_toolset_20260801",
    "toolset_name": "browser",
    "sdk": "@anthropic-ai/sdk",
    "sdk_version": "0.132.0"
  },
  "batch_halt_text": "Not executed: an earlier action in this turn failed.",
  "model_frame": {
    "max_long_edge": 1568,
    "max_pixels": 1150000,
    "rule": "Screenshots are downscaled (never upscaled) to fit long edge <= max_long_edge and width*height <= max_pixels, keeping aspect. Coordinates the model sends are in that frame; the executor scales them to screen pixels. The executor is the only place scaling happens."
  },
  "coordinate_spaces": {
    "pixels": "Model-frame pixels (default).",
    "normalized_1000": "A 0..1000 grid over the screen on both axes (UI-TARS / Qwen-VL style); x_screen = round(x / 1000 * screen_width)."
  },
  "risk_classes": {
    "reversible": "aci_safety::ConfirmationClass::Reversible",
    "risky": "aci_safety::ConfirmationClass::Risky",
    "irreversible": "aci_safety::ConfirmationClass::Irreversible"
  },
  "confirm_rules": {
    "never": "No human approval.",
    "non_sandbox": "Needs a single-use action-hash approval grant on non-sandbox targets (this-device, paired computers). Sandboxed targets (cloud/bot computers, gateway browser sessions) run it without approval.",
    "always": "Always needs a single-use action-hash approval grant.",
    "irreversible": "Any member whose risk is irreversible needs a grant, whatever its confirm rule."
  },
  "result_shape": {
    "type": "object",
    "required": [
      "is_error",
      "content",
      "screen"
    ],
    "properties": {
      "is_error": {
        "type": "boolean"
      },
      "content": {
        "type": "array",
        "items": {
          "anyOf": [
            {
              "type": "object",
              "required": [
                "type",
                "text"
              ],
              "properties": {
                "type": {
                  "const": "text"
                },
                "text": {
                  "type": "string"
                }
              }
            },
            {
              "type": "object",
              "required": [
                "type",
                "media_type",
                "data"
              ],
              "properties": {
                "type": {
                  "const": "image"
                },
                "media_type": {
                  "type": "string"
                },
                "data": {
                  "type": "string",
                  "description": "base64, no data: prefix"
                }
              }
            }
          ]
        }
      },
      "browser_state": {
        "type": "object",
        "required": [
          "tabs"
        ],
        "properties": {
          "tabs": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "tab_id",
                "title",
                "url"
              ],
              "properties": {
                "tab_id": {
                  "type": "string"
                },
                "title": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                },
                "active": {
                  "type": "boolean"
                }
              }
            }
          },
          "state_changes": {
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        }
      },
      "screen": {
        "type": "object",
        "required": [
          "width",
          "height",
          "scale"
        ],
        "properties": {
          "width": {
            "type": "integer",
            "description": "screen (or viewport) width in px"
          },
          "height": {
            "type": "integer"
          },
          "scale": {
            "type": "number",
            "description": "screen px per model-frame px (>= 1)"
          },
          "frame_width": {
            "type": "integer"
          },
          "frame_height": {
            "type": "integer"
          }
        }
      }
    }
  },
  "members": [
    {
      "name": "navigate",
      "description": "Navigate to a URL, or go back/forward/reload in history. The protocol may be omitted (defaults to https://).",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "navigate",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "description": "The URL to navigate to, or \"back\" / \"forward\" / \"reload\" for history navigation."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "url"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "screenshot",
      "description": "Capture the current browser viewport.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "screenshot",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "zoom",
      "description": "Return a cropped screenshot of the given viewport region, scaled up for closer inspection — useful for small icons, buttons, or text. Coordinates are in the same viewport-pixel space as a full screenshot.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "screenshot",
      "scale_fields": {
        "region": "rect"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "region": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 4,
            "maxItems": 4,
            "description": "[x0, y0, x1, y1] in viewport pixels."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "region"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "left_click",
      "description": "Left-click at a viewport coordinate or on an element by reference.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Clicked.",
      "scale_fields": {
        "target": "target"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "coordinate"
                  },
                  "x": {
                    "type": "number",
                    "description": "Pixels from the left edge of the viewport."
                  },
                  "y": {
                    "type": "number",
                    "description": "Pixels from the top edge of the viewport."
                  }
                },
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "additionalProperties": false,
                "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
              },
              {
                "type": "object",
                "properties": {
                  "ref": {
                    "type": "string",
                    "description": "An element reference (e.g. \"ref_7\") returned by a prior `read_page` or `find` result."
                  },
                  "type": {
                    "type": "string",
                    "const": "ref"
                  }
                },
                "required": [
                  "ref",
                  "type"
                ],
                "additionalProperties": false,
                "description": "An element on the page, identified by a reference from a prior `read_page` or `find` result. References are scoped to the tab that produced them and become stale after navigation or a major re-render."
              }
            ],
            "description": "Where to act: either a viewport coordinate or an element reference."
          },
          "modifiers": {
            "type": "string",
            "description": "Optional modifier key chord to hold for the duration of this action (e.g. \"shift\", \"ctrl+shift\", \"cmd+alt\")."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "right_click",
      "description": "Right-click at a viewport coordinate or on an element by reference.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Right-clicked.",
      "scale_fields": {
        "target": "target"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "coordinate"
                  },
                  "x": {
                    "type": "number",
                    "description": "Pixels from the left edge of the viewport."
                  },
                  "y": {
                    "type": "number",
                    "description": "Pixels from the top edge of the viewport."
                  }
                },
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "additionalProperties": false,
                "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
              },
              {
                "type": "object",
                "properties": {
                  "ref": {
                    "type": "string",
                    "description": "An element reference (e.g. \"ref_7\") returned by a prior `read_page` or `find` result."
                  },
                  "type": {
                    "type": "string",
                    "const": "ref"
                  }
                },
                "required": [
                  "ref",
                  "type"
                ],
                "additionalProperties": false,
                "description": "An element on the page, identified by a reference from a prior `read_page` or `find` result. References are scoped to the tab that produced them and become stale after navigation or a major re-render."
              }
            ],
            "description": "Where to act: either a viewport coordinate or an element reference."
          },
          "modifiers": {
            "type": "string",
            "description": "Optional modifier key chord to hold for the duration of this action (e.g. \"shift\", \"ctrl+shift\", \"cmd+alt\")."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "middle_click",
      "description": "Middle-click at a viewport coordinate or on an element by reference.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Middle-clicked.",
      "scale_fields": {
        "target": "target"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "coordinate"
                  },
                  "x": {
                    "type": "number",
                    "description": "Pixels from the left edge of the viewport."
                  },
                  "y": {
                    "type": "number",
                    "description": "Pixels from the top edge of the viewport."
                  }
                },
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "additionalProperties": false,
                "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
              },
              {
                "type": "object",
                "properties": {
                  "ref": {
                    "type": "string",
                    "description": "An element reference (e.g. \"ref_7\") returned by a prior `read_page` or `find` result."
                  },
                  "type": {
                    "type": "string",
                    "const": "ref"
                  }
                },
                "required": [
                  "ref",
                  "type"
                ],
                "additionalProperties": false,
                "description": "An element on the page, identified by a reference from a prior `read_page` or `find` result. References are scoped to the tab that produced them and become stale after navigation or a major re-render."
              }
            ],
            "description": "Where to act: either a viewport coordinate or an element reference."
          },
          "modifiers": {
            "type": "string",
            "description": "Optional modifier key chord to hold for the duration of this action (e.g. \"shift\", \"ctrl+shift\", \"cmd+alt\")."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "double_click",
      "description": "Double left-click at a viewport coordinate or on an element by reference.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Double-clicked.",
      "scale_fields": {
        "target": "target"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "coordinate"
                  },
                  "x": {
                    "type": "number",
                    "description": "Pixels from the left edge of the viewport."
                  },
                  "y": {
                    "type": "number",
                    "description": "Pixels from the top edge of the viewport."
                  }
                },
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "additionalProperties": false,
                "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
              },
              {
                "type": "object",
                "properties": {
                  "ref": {
                    "type": "string",
                    "description": "An element reference (e.g. \"ref_7\") returned by a prior `read_page` or `find` result."
                  },
                  "type": {
                    "type": "string",
                    "const": "ref"
                  }
                },
                "required": [
                  "ref",
                  "type"
                ],
                "additionalProperties": false,
                "description": "An element on the page, identified by a reference from a prior `read_page` or `find` result. References are scoped to the tab that produced them and become stale after navigation or a major re-render."
              }
            ],
            "description": "Where to act: either a viewport coordinate or an element reference."
          },
          "modifiers": {
            "type": "string",
            "description": "Optional modifier key chord to hold for the duration of this action (e.g. \"shift\", \"ctrl+shift\", \"cmd+alt\")."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "triple_click",
      "description": "Triple left-click at a viewport coordinate or on an element by reference (typically selects a line or paragraph).",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Triple-clicked.",
      "scale_fields": {
        "target": "target"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "coordinate"
                  },
                  "x": {
                    "type": "number",
                    "description": "Pixels from the left edge of the viewport."
                  },
                  "y": {
                    "type": "number",
                    "description": "Pixels from the top edge of the viewport."
                  }
                },
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "additionalProperties": false,
                "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
              },
              {
                "type": "object",
                "properties": {
                  "ref": {
                    "type": "string",
                    "description": "An element reference (e.g. \"ref_7\") returned by a prior `read_page` or `find` result."
                  },
                  "type": {
                    "type": "string",
                    "const": "ref"
                  }
                },
                "required": [
                  "ref",
                  "type"
                ],
                "additionalProperties": false,
                "description": "An element on the page, identified by a reference from a prior `read_page` or `find` result. References are scoped to the tab that produced them and become stale after navigation or a major re-render."
              }
            ],
            "description": "Where to act: either a viewport coordinate or an element reference."
          },
          "modifiers": {
            "type": "string",
            "description": "Optional modifier key chord to hold for the duration of this action (e.g. \"shift\", \"ctrl+shift\", \"cmd+alt\")."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "hover",
      "description": "Move the cursor to a coordinate or element without clicking.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Hovered.",
      "scale_fields": {
        "target": "target"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "const": "coordinate"
                  },
                  "x": {
                    "type": "number",
                    "description": "Pixels from the left edge of the viewport."
                  },
                  "y": {
                    "type": "number",
                    "description": "Pixels from the top edge of the viewport."
                  }
                },
                "required": [
                  "type",
                  "x",
                  "y"
                ],
                "additionalProperties": false,
                "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
              },
              {
                "type": "object",
                "properties": {
                  "ref": {
                    "type": "string",
                    "description": "An element reference (e.g. \"ref_7\") returned by a prior `read_page` or `find` result."
                  },
                  "type": {
                    "type": "string",
                    "const": "ref"
                  }
                },
                "required": [
                  "ref",
                  "type"
                ],
                "additionalProperties": false,
                "description": "An element on the page, identified by a reference from a prior `read_page` or `find` result. References are scoped to the tab that produced them and become stale after navigation or a major re-render."
              }
            ],
            "description": "Where to act: either a viewport coordinate or an element reference."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "left_click_drag",
      "description": "Press at `from`, drag to `target`, release. Both must be coordinate targets.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Dragged.",
      "scale_fields": {
        "from": "target",
        "target": "target"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "from": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "coordinate"
              },
              "x": {
                "type": "number",
                "description": "Pixels from the left edge of the viewport."
              },
              "y": {
                "type": "number",
                "description": "Pixels from the top edge of the viewport."
              }
            },
            "required": [
              "type",
              "x",
              "y"
            ],
            "additionalProperties": false,
            "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
          },
          "target": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "coordinate"
              },
              "x": {
                "type": "number",
                "description": "Pixels from the left edge of the viewport."
              },
              "y": {
                "type": "number",
                "description": "Pixels from the top edge of the viewport."
              }
            },
            "required": [
              "type",
              "x",
              "y"
            ],
            "additionalProperties": false,
            "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "from",
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "left_mouse_down",
      "description": "Press and hold the left mouse button at a viewport coordinate. Pair with left_mouse_up to perform a custom drag.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Mouse button pressed.",
      "scale_fields": {
        "target": "target"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "coordinate"
              },
              "x": {
                "type": "number",
                "description": "Pixels from the left edge of the viewport."
              },
              "y": {
                "type": "number",
                "description": "Pixels from the top edge of the viewport."
              }
            },
            "required": [
              "type",
              "x",
              "y"
            ],
            "additionalProperties": false,
            "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "left_mouse_up",
      "description": "Release the left mouse button at a viewport coordinate.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Mouse button released.",
      "scale_fields": {
        "target": "target"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "coordinate"
              },
              "x": {
                "type": "number",
                "description": "Pixels from the left edge of the viewport."
              },
              "y": {
                "type": "number",
                "description": "Pixels from the top edge of the viewport."
              }
            },
            "required": [
              "type",
              "x",
              "y"
            ],
            "additionalProperties": false,
            "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "mouse_move",
      "description": "Move the pointer to a viewport coordinate without clicking.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Moved the mouse.",
      "scale_fields": {
        "target": "target"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "coordinate"
              },
              "x": {
                "type": "number",
                "description": "Pixels from the left edge of the viewport."
              },
              "y": {
                "type": "number",
                "description": "Pixels from the top edge of the viewport."
              }
            },
            "required": [
              "type",
              "x",
              "y"
            ],
            "additionalProperties": false,
            "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "scroll",
      "description": "Scroll at a viewport position. `target` must be a coordinate target.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Scrolled {scroll_direction}.",
      "scale_fields": {
        "target": "target"
      },
      "input_schema": {
        "type": "object",
        "properties": {
          "scroll_direction": {
            "type": "string",
            "enum": [
              "up",
              "down",
              "left",
              "right"
            ]
          },
          "target": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "const": "coordinate"
              },
              "x": {
                "type": "number",
                "description": "Pixels from the left edge of the viewport."
              },
              "y": {
                "type": "number",
                "description": "Pixels from the top edge of the viewport."
              }
            },
            "required": [
              "type",
              "x",
              "y"
            ],
            "additionalProperties": false,
            "description": "A point in the browser viewport, in viewport pixels (the same frame as a full-viewport screenshot)."
          },
          "scroll_amount": {
            "type": "number",
            "description": "Scroll-wheel notches (1–10). Default 3."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "scroll_direction",
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "scroll_to",
      "description": "Scroll an element into view.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Scrolled to {ref}.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "type": "object",
            "properties": {
              "ref": {
                "type": "string",
                "description": "An element reference (e.g. \"ref_7\") returned by a prior `read_page` or `find` result."
              },
              "type": {
                "type": "string",
                "const": "ref"
              }
            },
            "required": [
              "ref",
              "type"
            ],
            "additionalProperties": false,
            "description": "An element on the page, identified by a reference from a prior `read_page` or `find` result. References are scoped to the tab that produced them and become stale after navigation or a major re-render."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "type",
      "description": "Type a literal string at the current focus.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": true,
      "confirm": "non_sandbox",
      "result_kind": "none",
      "ack_text": "Typed.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "description": "The text to type."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "text"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "key",
      "description": "Press a key or key chord. Use \"+\" to combine modifiers with a key (e.g. \"ctrl+a\", \"cmd+shift+p\") and space to sequence presses (e.g. \"Backspace Backspace Delete\"). Common names like \"Return\", \"Tab\", \"Escape\", \"BackSpace\" are supported.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": true,
      "confirm": "non_sandbox",
      "result_kind": "none",
      "ack_text": "Pressed {text}.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "description": "The key, chord, or space-separated sequence to press."
          },
          "repeat": {
            "type": "number",
            "description": "Number of times to repeat. Default 1."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "text"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "hold_key",
      "description": "Hold a key or key chord down for a duration, then release it. Uses the same key names and \"+\" chord syntax as the key action.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": true,
      "confirm": "non_sandbox",
      "result_kind": "none",
      "ack_text": "Held {text} for {duration}s.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "duration": {
            "type": "number",
            "description": "Seconds to hold the key down (maximum 30)."
          },
          "text": {
            "type": "string",
            "description": "The key or chord to hold."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "duration",
          "text"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "wait",
      "description": "Pause for the given duration.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "ack_text": "Waited {duration}s.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "duration": {
            "type": "number",
            "description": "Seconds to wait (maximum 30)."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "duration"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "read_page",
      "description": "Return a structured accessibility tree of the page (or the subtree rooted at `ref`), with element references like [ref_7] that can be used as targets on later actions. Output is capped at 50,000 characters — narrow with `ref` or a smaller `depth` when exceeded.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "text",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "depth": {
            "type": "number",
            "description": "Maximum tree depth. Default 15."
          },
          "filter": {
            "type": "string",
            "enum": [
              "all",
              "interactive"
            ],
            "description": "Which elements to include. Omitted: every visible element. \"interactive\": interactive elements only. \"all\": additionally includes off-viewport elements."
          },
          "ref": {
            "type": "string",
            "description": "Element reference to read a subtree from. Omit to read from the page root."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "find",
      "description": "Find elements matching a natural-language description (e.g. \"search bar\", \"add to cart button\") and return up to 20 matches with element references.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "text",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "description": "Natural-language description of the element(s) to find."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "query"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "get_page_text",
      "description": "Return the page's visible text content as plain text, prioritizing article content. Suited to articles, documentation, and other text-heavy pages.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "text",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "form_input",
      "description": "Set the value of a form element (input, textarea, select, checkbox). Use a boolean for checkboxes, an option value or text for selects.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": true,
      "confirm": "non_sandbox",
      "result_kind": "none",
      "ack_text": "Set the value of {ref}.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "type": "object",
            "properties": {
              "ref": {
                "type": "string",
                "description": "An element reference (e.g. \"ref_7\") returned by a prior `read_page` or `find` result."
              },
              "type": {
                "type": "string",
                "const": "ref"
              }
            },
            "required": [
              "ref",
              "type"
            ],
            "additionalProperties": false,
            "description": "An element on the page, identified by a reference from a prior `read_page` or `find` result. References are scoped to the tab that produced them and become stale after navigation or a major re-render."
          },
          "value": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "number"
              },
              {
                "type": "boolean"
              }
            ],
            "description": "The value to set."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target",
          "value"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "file_upload",
      "description": "Set the value of a file-input element to one or more files. The target must be an element reference; at least one of paths or document_ids is required.",
      "risk": "irreversible",
      "default_enabled": false,
      "needs_confirm": true,
      "confirm": "always",
      "result_kind": "none",
      "ack_text": "Uploaded.",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "target": {
            "type": "object",
            "properties": {
              "ref": {
                "type": "string",
                "description": "An element reference (e.g. \"ref_7\") returned by a prior `read_page` or `find` result."
              },
              "type": {
                "type": "string",
                "const": "ref"
              }
            },
            "required": [
              "ref",
              "type"
            ],
            "additionalProperties": false,
            "description": "An element on the page, identified by a reference from a prior `read_page` or `find` result. References are scoped to the tab that produced them and become stale after navigation or a major re-render."
          },
          "document_ids": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "References to files the harness has staged, for deployments where the browser executor cannot read the caller's filesystem."
          },
          "paths": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "File paths on the browser executor's filesystem."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "target"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "read_console",
      "description": "Return console output (log entries, errors, warnings) accumulated since the driver attached to the tab and since the last read, one line per entry. An empty result does not mean no traffic for a tab that predates attach.",
      "risk": "reversible",
      "default_enabled": false,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "text",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "read_network",
      "description": "Return the network requests (method, URL, status, MIME type, timing) recorded since the driver attached to the tab and since the last read, one line per entry. An empty result does not mean no traffic for a tab that predates attach.",
      "risk": "reversible",
      "default_enabled": false,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "text",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "javascript_exec",
      "description": "Execute JavaScript in the page context and return the value of the last expression. The code runs with access to the DOM, `window`, and page variables. Write the expression you want evaluated — do NOT use `return`.",
      "risk": "irreversible",
      "default_enabled": false,
      "needs_confirm": true,
      "confirm": "always",
      "result_kind": "text",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "description": "JavaScript to execute in the page context."
          },
          "tab_id": {
            "type": "string",
            "description": "Tab to act on. Defaults to the active tab when omitted."
          }
        },
        "required": [
          "text"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "new_tab",
      "description": "Open a new empty tab and return its tab_id.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "tab",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "list_tabs",
      "description": "List all open tabs with each tab's tab_id, title, and URL.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "tabs",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": false
      }
    },
    {
      "name": "switch_tab",
      "description": "Make the tab with the given tab_id the active tab — the tab that actions without a tab_id apply to.",
      "risk": "reversible",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "tab",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "tab_id": {
            "type": "string",
            "description": "The tab to switch to."
          }
        },
        "required": [
          "tab_id"
        ],
        "additionalProperties": false
      }
    },
    {
      "name": "close_tab",
      "description": "Close the tab with the given tab_id.",
      "risk": "risky",
      "default_enabled": true,
      "needs_confirm": false,
      "confirm": "never",
      "result_kind": "none",
      "scale_fields": {},
      "input_schema": {
        "type": "object",
        "properties": {
          "tab_id": {
            "type": "string",
            "description": "The tab to close."
          }
        },
        "required": [
          "tab_id"
        ],
        "additionalProperties": false
      }
    }
  ]
} as const;

export type ToolsetName = "computer" | "browser";
export type RiskClass = "reversible" | "risky" | "irreversible";
export type ConfirmRule = "never" | "non_sandbox" | "always";
export interface ToolsetMemberSpec {
  name: string;
  description: string;
  risk: RiskClass;
  default_enabled: boolean;
  needs_confirm: boolean;
  confirm: ConfirmRule;
  result_kind: string;
  ack_text?: string;
  scale_fields: Record<string, string>;
  input_schema: Record<string, unknown>;
}
export interface ToolsetContract {
  id: string;
  toolset: ToolsetName;
  version: number;
  upstream: { anthropic_type: string; toolset_name: string; sdk: string; sdk_version: string };
  batch_halt_text: string;
  model_frame: { max_long_edge: number; max_pixels: number; rule: string };
  members: readonly ToolsetMemberSpec[];
}
export type ToolsetContent =
  | { type: "text"; text: string }
  | { type: "image"; media_type: string; data: string };
export interface BrowserStateTab { tab_id: string; title: string; url: string; active?: boolean }
export interface BrowserState { tabs: BrowserStateTab[]; state_changes?: Array<Record<string, unknown>> }
/** Executor result: POST /computers/:id/toolset. */
export interface ToolsetResult {
  is_error: boolean;
  content: ToolsetContent[];
  browser_state?: BrowserState;
  screen: { width: number; height: number; scale: number; frame_width?: number; frame_height?: number };
}
/** Executor request body: POST /computers/:id/toolset. */
export interface ToolsetRequest {
  toolset: ToolsetName;
  member: string;
  input: Record<string, unknown>;
  run_id?: string;
  turn_id?: string;
  call_index?: number;
  model_frame?: { width: number; height: number };
  coordinate_space?: "pixels" | "normalized_1000";
  approval_grant?: string;
  browser_session_id?: string;
}
export const CONTRACTS: Record<ToolsetName, ToolsetContract> = {
  computer: COMPUTER_CONTRACT as unknown as ToolsetContract,
  browser: BROWSER_CONTRACT as unknown as ToolsetContract,
};
