#!/usr/bin/env node
// Generates typed bindings for the Allternit computer / browser toolset
// contracts (allternit-computer-v1.json, allternit-computer-v2.json,
// allternit-browser-v1.json).
//
//   node contracts/computer-toolset/generate.mjs           # write outputs
//   node contracts/computer-toolset/generate.mjs --check   # exit 1 on drift
//
// Outputs (never edit them by hand):
//   sdk/computer-toolset/src/generated.ts
//   cmd/gizzi-code/src/runtime/tools/computer-toolset/contract.gen.ts
//   domains/computer-use/core/contracts/toolset_v1.py
//
// Rust (allternit-api) reads the JSON directly with include_str!, so it has
// no generated copy to drift.
//
// The computer toolset has two contract generations: v1 is the 17-member
// pixel set (byte-identical to Anthropic's computer_toolset_20260801 and the
// member list the Claude-native wire entry may carry); v2 is additive (the
// same 17 plus 10 structured members backed by the Allternit Driver). TS
// keeps `CONTRACTS.computer` on v1 because the Claude-native configs loop
// must only name native members; v2 is exported as COMPUTER_V2_CONTRACT.
// Python keys CONTRACTS["computer"] at v2 (a superset: membership checks
// pass for both generations, so the Python engine forwards v2 members to
// the Rust executor).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '../..');
const check = process.argv.includes('--check');

const contracts = [
  { file: 'allternit-computer-v1.json', prefix: 'COMPUTER' },
  { file: 'allternit-computer-v2.json', prefix: 'COMPUTER_V2' },
  { file: 'allternit-browser-v1.json', prefix: 'BROWSER' },
].map((c) => ({ ...c, ...JSON.parse(fs.readFileSync(path.join(here, c.file), 'utf8')) }));

const pascal = (s) => s.split(/[_-]/).map((w) => w[0].toUpperCase() + w.slice(1)).join('');
const Pascal = (s) => pascal(s.toLowerCase());
const HEADER = 'Generated by contracts/computer-toolset/generate.mjs from contracts/computer-toolset/*.json. Do not edit.';

// ---------------------------------------------------------------- TypeScript
function tsType(s) {
  if (s.anyOf) return s.anyOf.map(tsType).join(' | ');
  if (s.const !== undefined) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(' | ');
  switch (s.type) {
    case 'string':
      return 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return `Array<${tsType(s.items)}>`;
    case 'object': {
      const req = new Set(s.required || []);
      const fields = Object.entries(s.properties || {}).map(
        ([k, v]) => `${k}${req.has(k) ? '' : '?'}: ${tsType(v)}${req.has(k) ? '' : ' | null'}`,
      );
      return fields.length ? `{ ${fields.join('; ')} }` : 'Record<string, never>';
    }
    default:
      throw new Error(`unsupported schema ${JSON.stringify(s)}`);
  }
}

function genTs() {
  const out = [`// ${HEADER}`, '/* eslint-disable */', ''];
  for (const c of contracts) {
    const P = Pascal(c.prefix);
    const names = c.prefix + '_MEMBER_NAMES';
    out.push(`// ---- ${c.id} (${c.upstream.anthropic_type}) ----`);
    out.push(`export const ${names} = ${JSON.stringify(c.members.map((m) => m.name))} as const;`);
    out.push(`export type ${P}MemberName = (typeof ${names})[number];`);
    for (const m of c.members) {
      out.push(`/** ${m.description.replace(/\*\//g, '*\\/')} */`);
      out.push(`export type ${P}${pascal(m.name)}Input = ${tsType(m.input_schema)};`);
    }
    out.push(`export interface ${P}MemberInputs {`);
    for (const m of c.members) out.push(`  ${m.name}: ${P}${pascal(m.name)}Input;`);
    out.push('}');
    const { file: _file, prefix: _prefix, ...clean } = c;
    out.push(`export const ${c.prefix}_CONTRACT = ${JSON.stringify(clean, null, 2)} as const;`);
    out.push('');
  }
  out.push('export type ToolsetName = "computer" | "browser";');
  out.push('export type RiskClass = "reversible" | "risky" | "irreversible";');
  out.push('export type ConfirmRule = "never" | "non_sandbox" | "always";');
  out.push(`export interface ToolsetMemberSpec {
  name: string;
  description: string;
  risk: RiskClass;
  default_enabled: boolean;
  needs_confirm: boolean;
  confirm: ConfirmRule;
  result_kind: string;
  ack_text?: string;
  scale_fields: Record<string, string>;
  input_schema: Record<string, unknown>;
}`);
  out.push(`export interface ToolsetContract {
  id: string;
  toolset: ToolsetName;
  version: number;
  upstream: { anthropic_type: string; toolset_name: string; sdk: string; sdk_version: string };
  batch_halt_text: string;
  model_frame: { max_long_edge: number; max_pixels: number; rule: string };
  members: readonly ToolsetMemberSpec[];
}`);
  out.push(`export type ToolsetContent =
  | { type: "text"; text: string }
  | { type: "image"; media_type: string; data: string };
export interface BrowserStateTab { tab_id: string; title: string; url: string; active?: boolean }
export interface BrowserState { tabs: BrowserStateTab[]; state_changes?: Array<Record<string, unknown>> }
/** Executor result: POST /computers/:id/toolset. */
export interface ToolsetResult {
  is_error: boolean;
  content: ToolsetContent[];
  browser_state?: BrowserState;
  screen: { width: number; height: number; scale: number; frame_width?: number; frame_height?: number };
}
/** Executor request body: POST /computers/:id/toolset. */
export interface ToolsetRequest {
  toolset: ToolsetName;
  member: string;
  input: Record<string, unknown>;
  run_id?: string;
  turn_id?: string;
  call_index?: number;
  model_frame?: { width: number; height: number };
  coordinate_space?: "pixels" | "normalized_1000";
  approval_grant?: string;
  browser_session_id?: string;
}
export const CONTRACTS: Record<ToolsetName, ToolsetContract> = {
  computer: COMPUTER_CONTRACT as unknown as ToolsetContract,
  browser: BROWSER_CONTRACT as unknown as ToolsetContract,
};
/** allternit.computer.v2: the 17 pixel members plus the 8 driver-backed structured members. */
export const COMPUTER_V2 = COMPUTER_V2_CONTRACT as unknown as ToolsetContract;
/** Every member of allternit.computer.v2 (the 17 pixel members, then read_ui, act, run_batch, verify, request_human, use_credential, run_subtask, run_parallel, run_skill, skills). */
export const COMPUTER_V2_MEMBER_LIST = COMPUTER_V2.members;`);
  return out.join('\n') + '\n';
}

// -------------------------------------------------------------------- Python
function pyType(s) {
  if (s.anyOf) return `Union[${s.anyOf.map(pyType).join(', ')}]`;
  if (s.const !== undefined) return `Literal[${JSON.stringify(s.const)}]`;
  if (s.enum) return `Literal[${s.enum.map((v) => JSON.stringify(v)).join(', ')}]`;
  switch (s.type) {
    case 'string':
      return 'str';
    case 'number':
      return 'float';
    case 'integer':
      return 'int';
    case 'boolean':
      return 'bool';
    case 'array':
      return `List[${pyType(s.items)}]`;
    case 'object':
      return 'Dict[str, Any]';
    default:
      throw new Error(`unsupported schema ${JSON.stringify(s)}`);
  }
}

const PY_KEYWORDS = new Set(['from', 'import', 'class', 'def', 'return', 'pass', 'global', 'lambda', 'in', 'is', 'not', 'and', 'or', 'with', 'as', 'type_']);

function genPy() {
  const out = [
    `"""${HEADER}"""`,
    '# fmt: off',
    'from __future__ import annotations',
    '',
    'import json',
    'from typing import Any, Dict, List, Literal, Optional, TypedDict, Union',
    '',
  ];
  for (const c of contracts) {
    const P = Pascal(c.prefix);
    const names = `${c.prefix}_MEMBER_NAMES`;
    out.push(`# ---- ${c.id} (${c.upstream.anthropic_type}) ----`);
    out.push(`${names}: tuple = ${JSON.stringify(c.members.map((m) => m.name)).replace(/^\[/, '(').replace(/\]$/, ',)')}`);
    for (const m of c.members) {
      const name = `${P}${pascal(m.name)}Input`;
      const req = new Set(m.input_schema.required || []);
      const props = Object.entries(m.input_schema.properties || {});
      const reqProps = props.filter(([k]) => req.has(k));
      const optProps = props.filter(([k]) => !req.has(k));
      out.push('');
      // Functional form for the required half: field names such as `from`
      // are Python keywords and cannot appear in a class body.
      out.push(`_${name}Required = TypedDict(${JSON.stringify('_' + name + 'Required')}, {${reqProps.map(([k, v]) => `${JSON.stringify(k)}: ${pyType(v)}`).join(', ')}})`);
      out.push('');
      out.push('');
      out.push(`class ${name}(_${name}Required, total=False):`);
      out.push(`    """${m.description.replace(/"""/g, "'''").replace(/\\/g, '\\\\')}"""`);
      if (optProps.some(([k]) => PY_KEYWORDS.has(k))) throw new Error(`${name}: optional field is a Python keyword`);
      if (!optProps.length) out.push('');
      for (const [k, v] of optProps) out.push(`    ${k}: Optional[${pyType(v)}]`);
    }
    const { file: _f, prefix: _p, ...clean } = c;
    out.push('');
    out.push(`${c.prefix}_CONTRACT: Dict[str, Any] = json.loads(${JSON.stringify(JSON.stringify(clean))})`);
    out.push('');
  }
  out.push(`CONTRACTS: Dict[str, Dict[str, Any]] = {"computer": COMPUTER_V2_CONTRACT, "browser": BROWSER_CONTRACT}`);
  out.push('');
  out.push('');
  out.push('def member_spec(toolset: str, member: str) -> Optional[Dict[str, Any]]:');
  out.push('    """The contract row for one member, or None when it does not exist."""');
  out.push('    for row in CONTRACTS[toolset]["members"]:');
  out.push('        if row["name"] == member:');
  out.push('            return row');
  out.push('    return None');
  return out.join('\n') + '\n';
}

const ts = genTs();
const outputs = [
  ['sdk/computer-toolset/src/generated.ts', ts],
  ['cmd/gizzi-code/src/runtime/tools/computer-toolset/contract.gen.ts', ts],
  ['domains/computer-use/core/contracts/toolset_v1.py', genPy()],
];

let drift = false;
for (const [rel, content] of outputs) {
  const p = path.join(repo, rel);
  const current = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
  if (current === content) continue;
  if (check) {
    console.error(`drift: ${rel} is out of date (run node contracts/computer-toolset/generate.mjs)`);
    drift = true;
  } else {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
    console.log(`wrote ${rel}`);
  }
}
if (drift) process.exit(1);
if (check) console.log('computer-toolset contract bindings are up to date');
