//! Agent ISA: one enum variant per canonical primitive id (ABI 1.0.0).
//!
//! GENERATED from `spec/Contracts/kernel/v1/registry/primitives.json` (191 ids).
//! Do not hand-edit; a unit test fails if this drifts from the registry.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum AgentIsa {
    ObserveEnvironment,
    ListFiles,
    ReadFile,
    ReadRange,
    ReadSymbol,
    FindSymbol,
    FindReference,
    FindDefinition,
    SearchText,
    SearchSemantic,
    SearchFilename,
    ReadDiagnostics,
    ReadGitState,
    ReadDiff,
    ReadTestResults,
    ReadBuildOutput,
    ReadDependencies,
    ReadCallGraph,
    ReadTypeGraph,
    ReadRepoMap,
    ClassifyTask,
    ClassifyError,
    ClassifyFile,
    SelectScope,
    SelectFile,
    SelectSymbol,
    SelectTool,
    SelectTest,
    SelectStrategy,
    RankCandidates,
    AssessRisk,
    AssessCompleteness,
    AssessConfidence,
    AssessRegressionRisk,
    CreateFile,
    DeleteFile,
    MoveFile,
    RenameFile,
    ReplaceRange,
    ReplaceSymbol,
    InsertNode,
    DeleteNode,
    RenameSymbol,
    ApplyPatch,
    ApplyCodemod,
    UpdateDependency,
    UpdateConfig,
    RunCommand,
    RunScript,
    RunTest,
    RunTestSet,
    RunBuild,
    RunLinter,
    RunFormatter,
    RunTypecheck,
    RunBenchmark,
    Status,
    Diff,
    Blame,
    Log,
    Show,
    BranchInfo,
    Stage,
    Unstage,
    Restore,
    Parse,
    Compile,
    FormatCheck,
    Lint,
    Typecheck,
    UnitTest,
    IntegrationTest,
    BehaviorCheck,
    ApiCompatCheck,
    RegressionCheck,
    SecurityCheck,
    DiffReview,
    RequirementCheck,
    Branch,
    Parallel,
    Join,
    Retry,
    Rollback,
    Checkpoint,
    RequestEvidence,
    Escalate,
    WaitForDependency,
    Finish,
    ClassifyIntent,
    ClassifyRisk,
    ClassifyResource,
    IsComplete,
    IsRelevant,
    IsSupported,
    IsReversible,
    IsDuplicate,
    IsRegression,
    RiskLevel,
    ComplexityLevel,
    Urgency,
    Novelty,
    Impact,
    SelectModel,
    SelectBranch,
    RankDocuments,
    RankFiles,
    RankSymbols,
    RankPatches,
    RankPlans,
    SelectRelevantContext,
    SelectAffectedTests,
    SelectChangedDependencies,
    ExpectedSuccess,
    ExpectedCost,
    ExpectedLatency,
    ExpectedInformationGain,
    Continue,
    Review,
    Block,
    ParseTaskRequest,
    ExtractExplicitDeliverables,
    ExtractHardConstraints,
    InferAcceptanceCriteria,
    DetectAmbiguity,
    SelectClarifyOrDefault,
    InitializeTaskState,
    FingerprintEnvironment,
    DetectProjectRoots,
    DetectLanguages,
    DetectBuildSystem,
    ActivatePrimitivePacks,
    BuildRepoIndex,
    BuildSymbolGraph,
    BuildDependencyGraph,
    GenerateSearchIntent,
    RetrieveCandidateFiles,
    RetrieveCandidateSymbols,
    ExpandStructuralContext,
    ScoreContextRelevance,
    CompileModelContext,
    SelectWorkflowTemplate,
    InstantiateComputeGraph,
    ProposePlanBranches,
    ScorePlanBranch,
    PruneBranches,
    DetectInformationGap,
    SelectNextGraphNode,
    AssessCompletion,
    SelectToolFamily,
    SelectToolOperation,
    ResolveArgumentFromState,
    GenerateFreeArgument,
    ValidateToolSchema,
    AuthorizeToolCall,
    ExecuteTool,
    ClassifyToolFailure,
    SelectRecoveryAction,
    DefineMutationScope,
    SelectEditRepresentation,
    GeneratePatchCandidate,
    GenerateTestCandidate,
    ApplyPatchTransactionally,
    FormatChangedCode,
    UpdateAffectedContext,
    ComparePatchCandidates,
    ParseValidate,
    TypecheckAffected,
    RunTargetTests,
    ClassifyDiagnostic,
    LocalizeFailureCause,
    SelectRepairStrategy,
    RollbackMutation,
    VerifyRequirements,
    CheckUnresolvedFailures,
    CheckArtifactExistence,
    CheckAcceptanceEvidence,
    DecideFinishContinueEscalate,
    ComposeFinalReport,
    PersistRunReceipt,
    UpdateLongTermMemory,
    CloseTaskState,
    DescribeCognitiveRequirement,
    FilterEligibleModels,
    PredictModelSuccess,
    EstimateRouteCost,
    SelectLogicalModel,
    SelectStateTransferMode,
    PreloadModel,
    EvictModel,
    ValidateTranslatedState,
    ReconstructSemanticContext,
}

impl AgentIsa {
    pub const ALL: [AgentIsa; 191] = [
        AgentIsa::ObserveEnvironment,
        AgentIsa::ListFiles,
        AgentIsa::ReadFile,
        AgentIsa::ReadRange,
        AgentIsa::ReadSymbol,
        AgentIsa::FindSymbol,
        AgentIsa::FindReference,
        AgentIsa::FindDefinition,
        AgentIsa::SearchText,
        AgentIsa::SearchSemantic,
        AgentIsa::SearchFilename,
        AgentIsa::ReadDiagnostics,
        AgentIsa::ReadGitState,
        AgentIsa::ReadDiff,
        AgentIsa::ReadTestResults,
        AgentIsa::ReadBuildOutput,
        AgentIsa::ReadDependencies,
        AgentIsa::ReadCallGraph,
        AgentIsa::ReadTypeGraph,
        AgentIsa::ReadRepoMap,
        AgentIsa::ClassifyTask,
        AgentIsa::ClassifyError,
        AgentIsa::ClassifyFile,
        AgentIsa::SelectScope,
        AgentIsa::SelectFile,
        AgentIsa::SelectSymbol,
        AgentIsa::SelectTool,
        AgentIsa::SelectTest,
        AgentIsa::SelectStrategy,
        AgentIsa::RankCandidates,
        AgentIsa::AssessRisk,
        AgentIsa::AssessCompleteness,
        AgentIsa::AssessConfidence,
        AgentIsa::AssessRegressionRisk,
        AgentIsa::CreateFile,
        AgentIsa::DeleteFile,
        AgentIsa::MoveFile,
        AgentIsa::RenameFile,
        AgentIsa::ReplaceRange,
        AgentIsa::ReplaceSymbol,
        AgentIsa::InsertNode,
        AgentIsa::DeleteNode,
        AgentIsa::RenameSymbol,
        AgentIsa::ApplyPatch,
        AgentIsa::ApplyCodemod,
        AgentIsa::UpdateDependency,
        AgentIsa::UpdateConfig,
        AgentIsa::RunCommand,
        AgentIsa::RunScript,
        AgentIsa::RunTest,
        AgentIsa::RunTestSet,
        AgentIsa::RunBuild,
        AgentIsa::RunLinter,
        AgentIsa::RunFormatter,
        AgentIsa::RunTypecheck,
        AgentIsa::RunBenchmark,
        AgentIsa::Status,
        AgentIsa::Diff,
        AgentIsa::Blame,
        AgentIsa::Log,
        AgentIsa::Show,
        AgentIsa::BranchInfo,
        AgentIsa::Stage,
        AgentIsa::Unstage,
        AgentIsa::Restore,
        AgentIsa::Parse,
        AgentIsa::Compile,
        AgentIsa::FormatCheck,
        AgentIsa::Lint,
        AgentIsa::Typecheck,
        AgentIsa::UnitTest,
        AgentIsa::IntegrationTest,
        AgentIsa::BehaviorCheck,
        AgentIsa::ApiCompatCheck,
        AgentIsa::RegressionCheck,
        AgentIsa::SecurityCheck,
        AgentIsa::DiffReview,
        AgentIsa::RequirementCheck,
        AgentIsa::Branch,
        AgentIsa::Parallel,
        AgentIsa::Join,
        AgentIsa::Retry,
        AgentIsa::Rollback,
        AgentIsa::Checkpoint,
        AgentIsa::RequestEvidence,
        AgentIsa::Escalate,
        AgentIsa::WaitForDependency,
        AgentIsa::Finish,
        AgentIsa::ClassifyIntent,
        AgentIsa::ClassifyRisk,
        AgentIsa::ClassifyResource,
        AgentIsa::IsComplete,
        AgentIsa::IsRelevant,
        AgentIsa::IsSupported,
        AgentIsa::IsReversible,
        AgentIsa::IsDuplicate,
        AgentIsa::IsRegression,
        AgentIsa::RiskLevel,
        AgentIsa::ComplexityLevel,
        AgentIsa::Urgency,
        AgentIsa::Novelty,
        AgentIsa::Impact,
        AgentIsa::SelectModel,
        AgentIsa::SelectBranch,
        AgentIsa::RankDocuments,
        AgentIsa::RankFiles,
        AgentIsa::RankSymbols,
        AgentIsa::RankPatches,
        AgentIsa::RankPlans,
        AgentIsa::SelectRelevantContext,
        AgentIsa::SelectAffectedTests,
        AgentIsa::SelectChangedDependencies,
        AgentIsa::ExpectedSuccess,
        AgentIsa::ExpectedCost,
        AgentIsa::ExpectedLatency,
        AgentIsa::ExpectedInformationGain,
        AgentIsa::Continue,
        AgentIsa::Review,
        AgentIsa::Block,
        AgentIsa::ParseTaskRequest,
        AgentIsa::ExtractExplicitDeliverables,
        AgentIsa::ExtractHardConstraints,
        AgentIsa::InferAcceptanceCriteria,
        AgentIsa::DetectAmbiguity,
        AgentIsa::SelectClarifyOrDefault,
        AgentIsa::InitializeTaskState,
        AgentIsa::FingerprintEnvironment,
        AgentIsa::DetectProjectRoots,
        AgentIsa::DetectLanguages,
        AgentIsa::DetectBuildSystem,
        AgentIsa::ActivatePrimitivePacks,
        AgentIsa::BuildRepoIndex,
        AgentIsa::BuildSymbolGraph,
        AgentIsa::BuildDependencyGraph,
        AgentIsa::GenerateSearchIntent,
        AgentIsa::RetrieveCandidateFiles,
        AgentIsa::RetrieveCandidateSymbols,
        AgentIsa::ExpandStructuralContext,
        AgentIsa::ScoreContextRelevance,
        AgentIsa::CompileModelContext,
        AgentIsa::SelectWorkflowTemplate,
        AgentIsa::InstantiateComputeGraph,
        AgentIsa::ProposePlanBranches,
        AgentIsa::ScorePlanBranch,
        AgentIsa::PruneBranches,
        AgentIsa::DetectInformationGap,
        AgentIsa::SelectNextGraphNode,
        AgentIsa::AssessCompletion,
        AgentIsa::SelectToolFamily,
        AgentIsa::SelectToolOperation,
        AgentIsa::ResolveArgumentFromState,
        AgentIsa::GenerateFreeArgument,
        AgentIsa::ValidateToolSchema,
        AgentIsa::AuthorizeToolCall,
        AgentIsa::ExecuteTool,
        AgentIsa::ClassifyToolFailure,
        AgentIsa::SelectRecoveryAction,
        AgentIsa::DefineMutationScope,
        AgentIsa::SelectEditRepresentation,
        AgentIsa::GeneratePatchCandidate,
        AgentIsa::GenerateTestCandidate,
        AgentIsa::ApplyPatchTransactionally,
        AgentIsa::FormatChangedCode,
        AgentIsa::UpdateAffectedContext,
        AgentIsa::ComparePatchCandidates,
        AgentIsa::ParseValidate,
        AgentIsa::TypecheckAffected,
        AgentIsa::RunTargetTests,
        AgentIsa::ClassifyDiagnostic,
        AgentIsa::LocalizeFailureCause,
        AgentIsa::SelectRepairStrategy,
        AgentIsa::RollbackMutation,
        AgentIsa::VerifyRequirements,
        AgentIsa::CheckUnresolvedFailures,
        AgentIsa::CheckArtifactExistence,
        AgentIsa::CheckAcceptanceEvidence,
        AgentIsa::DecideFinishContinueEscalate,
        AgentIsa::ComposeFinalReport,
        AgentIsa::PersistRunReceipt,
        AgentIsa::UpdateLongTermMemory,
        AgentIsa::CloseTaskState,
        AgentIsa::DescribeCognitiveRequirement,
        AgentIsa::FilterEligibleModels,
        AgentIsa::PredictModelSuccess,
        AgentIsa::EstimateRouteCost,
        AgentIsa::SelectLogicalModel,
        AgentIsa::SelectStateTransferMode,
        AgentIsa::PreloadModel,
        AgentIsa::EvictModel,
        AgentIsa::ValidateTranslatedState,
        AgentIsa::ReconstructSemanticContext,
    ];

    /// Canonical dotted primitive id.
    pub fn id(self) -> &'static str {
        match self {
            AgentIsa::ObserveEnvironment => "obs.observe_environment",
            AgentIsa::ListFiles => "obs.list_files",
            AgentIsa::ReadFile => "obs.read_file",
            AgentIsa::ReadRange => "obs.read_range",
            AgentIsa::ReadSymbol => "obs.read_symbol",
            AgentIsa::FindSymbol => "obs.find_symbol",
            AgentIsa::FindReference => "obs.find_reference",
            AgentIsa::FindDefinition => "obs.find_definition",
            AgentIsa::SearchText => "obs.search_text",
            AgentIsa::SearchSemantic => "obs.search_semantic",
            AgentIsa::SearchFilename => "obs.search_filename",
            AgentIsa::ReadDiagnostics => "obs.read_diagnostics",
            AgentIsa::ReadGitState => "obs.read_git_state",
            AgentIsa::ReadDiff => "obs.read_diff",
            AgentIsa::ReadTestResults => "obs.read_test_results",
            AgentIsa::ReadBuildOutput => "obs.read_build_output",
            AgentIsa::ReadDependencies => "obs.read_dependencies",
            AgentIsa::ReadCallGraph => "obs.read_call_graph",
            AgentIsa::ReadTypeGraph => "obs.read_type_graph",
            AgentIsa::ReadRepoMap => "obs.read_repo_map",
            AgentIsa::ClassifyTask => "dec.classify_task",
            AgentIsa::ClassifyError => "dec.classify_error",
            AgentIsa::ClassifyFile => "dec.classify_file",
            AgentIsa::SelectScope => "dec.select_scope",
            AgentIsa::SelectFile => "dec.select_file",
            AgentIsa::SelectSymbol => "dec.select_symbol",
            AgentIsa::SelectTool => "dec.select_tool",
            AgentIsa::SelectTest => "dec.select_test",
            AgentIsa::SelectStrategy => "dec.select_strategy",
            AgentIsa::RankCandidates => "dec.rank_candidates",
            AgentIsa::AssessRisk => "dec.assess_risk",
            AgentIsa::AssessCompleteness => "dec.assess_completeness",
            AgentIsa::AssessConfidence => "dec.assess_confidence",
            AgentIsa::AssessRegressionRisk => "dec.assess_regression_risk",
            AgentIsa::CreateFile => "mut.create_file",
            AgentIsa::DeleteFile => "mut.delete_file",
            AgentIsa::MoveFile => "mut.move_file",
            AgentIsa::RenameFile => "mut.rename_file",
            AgentIsa::ReplaceRange => "mut.replace_range",
            AgentIsa::ReplaceSymbol => "mut.replace_symbol",
            AgentIsa::InsertNode => "mut.insert_node",
            AgentIsa::DeleteNode => "mut.delete_node",
            AgentIsa::RenameSymbol => "mut.rename_symbol",
            AgentIsa::ApplyPatch => "mut.apply_patch",
            AgentIsa::ApplyCodemod => "mut.apply_codemod",
            AgentIsa::UpdateDependency => "mut.update_dependency",
            AgentIsa::UpdateConfig => "mut.update_config",
            AgentIsa::RunCommand => "tool.run_command",
            AgentIsa::RunScript => "tool.run_script",
            AgentIsa::RunTest => "tool.run_test",
            AgentIsa::RunTestSet => "tool.run_test_set",
            AgentIsa::RunBuild => "tool.run_build",
            AgentIsa::RunLinter => "tool.run_linter",
            AgentIsa::RunFormatter => "tool.run_formatter",
            AgentIsa::RunTypecheck => "tool.run_typecheck",
            AgentIsa::RunBenchmark => "tool.run_benchmark",
            AgentIsa::Status => "obs.vcs.status",
            AgentIsa::Diff => "obs.vcs.diff",
            AgentIsa::Blame => "obs.vcs.blame",
            AgentIsa::Log => "obs.vcs.log",
            AgentIsa::Show => "obs.vcs.show",
            AgentIsa::BranchInfo => "obs.vcs.branch_info",
            AgentIsa::Stage => "mut.vcs.stage",
            AgentIsa::Unstage => "mut.vcs.unstage",
            AgentIsa::Restore => "mut.vcs.restore",
            AgentIsa::Parse => "ver.parse",
            AgentIsa::Compile => "ver.compile",
            AgentIsa::FormatCheck => "ver.format_check",
            AgentIsa::Lint => "ver.lint",
            AgentIsa::Typecheck => "ver.typecheck",
            AgentIsa::UnitTest => "ver.unit_test",
            AgentIsa::IntegrationTest => "ver.integration_test",
            AgentIsa::BehaviorCheck => "ver.behavior_check",
            AgentIsa::ApiCompatCheck => "ver.api_compat_check",
            AgentIsa::RegressionCheck => "ver.regression_check",
            AgentIsa::SecurityCheck => "ver.security_check",
            AgentIsa::DiffReview => "ver.diff_review",
            AgentIsa::RequirementCheck => "ver.requirement_check",
            AgentIsa::Branch => "ctl.branch",
            AgentIsa::Parallel => "ctl.parallel",
            AgentIsa::Join => "ctl.join",
            AgentIsa::Retry => "ctl.retry",
            AgentIsa::Rollback => "ctl.rollback",
            AgentIsa::Checkpoint => "ctl.checkpoint",
            AgentIsa::RequestEvidence => "ctl.request_evidence",
            AgentIsa::Escalate => "ctl.escalate",
            AgentIsa::WaitForDependency => "ctl.wait_for_dependency",
            AgentIsa::Finish => "ctl.finish",
            AgentIsa::ClassifyIntent => "dec.classify_intent",
            AgentIsa::ClassifyRisk => "dec.classify_risk",
            AgentIsa::ClassifyResource => "dec.classify_resource",
            AgentIsa::IsComplete => "dec.is_complete",
            AgentIsa::IsRelevant => "dec.is_relevant",
            AgentIsa::IsSupported => "dec.is_supported",
            AgentIsa::IsReversible => "dec.is_reversible",
            AgentIsa::IsDuplicate => "dec.is_duplicate",
            AgentIsa::IsRegression => "dec.is_regression",
            AgentIsa::RiskLevel => "dec.risk_level",
            AgentIsa::ComplexityLevel => "dec.complexity_level",
            AgentIsa::Urgency => "dec.urgency",
            AgentIsa::Novelty => "dec.novelty",
            AgentIsa::Impact => "dec.impact",
            AgentIsa::SelectModel => "dec.select_model",
            AgentIsa::SelectBranch => "dec.select_branch",
            AgentIsa::RankDocuments => "dec.rank_documents",
            AgentIsa::RankFiles => "dec.rank_files",
            AgentIsa::RankSymbols => "dec.rank_symbols",
            AgentIsa::RankPatches => "dec.rank_patches",
            AgentIsa::RankPlans => "dec.rank_plans",
            AgentIsa::SelectRelevantContext => "dec.select_relevant_context",
            AgentIsa::SelectAffectedTests => "dec.select_affected_tests",
            AgentIsa::SelectChangedDependencies => "dec.select_changed_dependencies",
            AgentIsa::ExpectedSuccess => "dec.expected_success",
            AgentIsa::ExpectedCost => "dec.expected_cost",
            AgentIsa::ExpectedLatency => "dec.expected_latency",
            AgentIsa::ExpectedInformationGain => "dec.expected_information_gain",
            AgentIsa::Continue => "ctl.continue",
            AgentIsa::Review => "ctl.review",
            AgentIsa::Block => "ctl.block",
            AgentIsa::ParseTaskRequest => "obs.parse_task_request",
            AgentIsa::ExtractExplicitDeliverables => "obs.extract_explicit_deliverables",
            AgentIsa::ExtractHardConstraints => "obs.extract_hard_constraints",
            AgentIsa::InferAcceptanceCriteria => "dec.infer_acceptance_criteria",
            AgentIsa::DetectAmbiguity => "dec.detect_ambiguity",
            AgentIsa::SelectClarifyOrDefault => "dec.select_clarify_or_default",
            AgentIsa::InitializeTaskState => "state.initialize_task_state",
            AgentIsa::FingerprintEnvironment => "obs.fingerprint_environment",
            AgentIsa::DetectProjectRoots => "obs.detect_project_roots",
            AgentIsa::DetectLanguages => "obs.detect_languages",
            AgentIsa::DetectBuildSystem => "obs.detect_build_system",
            AgentIsa::ActivatePrimitivePacks => "state.activate_primitive_packs",
            AgentIsa::BuildRepoIndex => "obs.build_repo_index",
            AgentIsa::BuildSymbolGraph => "obs.build_symbol_graph",
            AgentIsa::BuildDependencyGraph => "obs.build_dependency_graph",
            AgentIsa::GenerateSearchIntent => "ctx.generate_search_intent",
            AgentIsa::RetrieveCandidateFiles => "ctx.retrieve_candidate_files",
            AgentIsa::RetrieveCandidateSymbols => "ctx.retrieve_candidate_symbols",
            AgentIsa::ExpandStructuralContext => "ctx.expand_structural_context",
            AgentIsa::ScoreContextRelevance => "dec.score_context_relevance",
            AgentIsa::CompileModelContext => "ctx.compile_model_context",
            AgentIsa::SelectWorkflowTemplate => "dec.select_workflow_template",
            AgentIsa::InstantiateComputeGraph => "plan.instantiate_compute_graph",
            AgentIsa::ProposePlanBranches => "plan.propose_plan_branches",
            AgentIsa::ScorePlanBranch => "dec.score_plan_branch",
            AgentIsa::PruneBranches => "plan.prune_branches",
            AgentIsa::DetectInformationGap => "plan.detect_information_gap",
            AgentIsa::SelectNextGraphNode => "dec.select_next_graph_node",
            AgentIsa::AssessCompletion => "dec.assess_completion",
            AgentIsa::SelectToolFamily => "dec.select_tool_family",
            AgentIsa::SelectToolOperation => "dec.select_tool_operation",
            AgentIsa::ResolveArgumentFromState => "tool.resolve_argument_from_state",
            AgentIsa::GenerateFreeArgument => "tool.generate_free_argument",
            AgentIsa::ValidateToolSchema => "tool.validate_tool_schema",
            AgentIsa::AuthorizeToolCall => "policy.authorize_tool_call",
            AgentIsa::ExecuteTool => "tool.execute",
            AgentIsa::ClassifyToolFailure => "dec.classify_tool_failure",
            AgentIsa::SelectRecoveryAction => "tool.recover",
            AgentIsa::DefineMutationScope => "mut.define_mutation_scope",
            AgentIsa::SelectEditRepresentation => "dec.select_edit_representation",
            AgentIsa::GeneratePatchCandidate => "mut.generate_patch_candidate",
            AgentIsa::GenerateTestCandidate => "mut.generate_test_candidate",
            AgentIsa::ApplyPatchTransactionally => "mut.apply_patch_transactionally",
            AgentIsa::FormatChangedCode => "mut.format_changed_code",
            AgentIsa::UpdateAffectedContext => "ctx.update_affected_context",
            AgentIsa::ComparePatchCandidates => "dec.compare_patch_candidates",
            AgentIsa::ParseValidate => "ver.parse_validate",
            AgentIsa::TypecheckAffected => "ver.typecheck_affected",
            AgentIsa::RunTargetTests => "ver.run_target_tests",
            AgentIsa::ClassifyDiagnostic => "dec.classify_diagnostic",
            AgentIsa::LocalizeFailureCause => "dec.localize_failure_cause",
            AgentIsa::SelectRepairStrategy => "dec.select_repair_strategy",
            AgentIsa::RollbackMutation => "ctl.rollback_mutation",
            AgentIsa::VerifyRequirements => "ver.verify_requirements",
            AgentIsa::CheckUnresolvedFailures => "ver.check_unresolved_failures",
            AgentIsa::CheckArtifactExistence => "ver.check_artifact_existence",
            AgentIsa::CheckAcceptanceEvidence => "ver.check_acceptance_evidence",
            AgentIsa::DecideFinishContinueEscalate => "dec.decide_finish_continue_escalate",
            AgentIsa::ComposeFinalReport => "ctl.compose_final_report",
            AgentIsa::PersistRunReceipt => "state.persist_run_receipt",
            AgentIsa::UpdateLongTermMemory => "mem.update_long_term_memory",
            AgentIsa::CloseTaskState => "state.close_task_state",
            AgentIsa::DescribeCognitiveRequirement => "route.describe_cognitive_requirement",
            AgentIsa::FilterEligibleModels => "route.filter_eligible_models",
            AgentIsa::PredictModelSuccess => "route.predict_model_success",
            AgentIsa::EstimateRouteCost => "route.estimate_route_cost",
            AgentIsa::SelectLogicalModel => "route.select_logical_model",
            AgentIsa::SelectStateTransferMode => "route.select_state_transfer_mode",
            AgentIsa::PreloadModel => "route.preload_model",
            AgentIsa::EvictModel => "route.evict_model",
            AgentIsa::ValidateTranslatedState => "state.validate_translated_state",
            AgentIsa::ReconstructSemanticContext => "ctx.reconstruct_semantic_context",
        }
    }

    pub fn from_id(id: &str) -> Option<AgentIsa> {
        match id {
            "obs.observe_environment" => Some(AgentIsa::ObserveEnvironment),
            "obs.list_files" => Some(AgentIsa::ListFiles),
            "obs.read_file" => Some(AgentIsa::ReadFile),
            "obs.read_range" => Some(AgentIsa::ReadRange),
            "obs.read_symbol" => Some(AgentIsa::ReadSymbol),
            "obs.find_symbol" => Some(AgentIsa::FindSymbol),
            "obs.find_reference" => Some(AgentIsa::FindReference),
            "obs.find_definition" => Some(AgentIsa::FindDefinition),
            "obs.search_text" => Some(AgentIsa::SearchText),
            "obs.search_semantic" => Some(AgentIsa::SearchSemantic),
            "obs.search_filename" => Some(AgentIsa::SearchFilename),
            "obs.read_diagnostics" => Some(AgentIsa::ReadDiagnostics),
            "obs.read_git_state" => Some(AgentIsa::ReadGitState),
            "obs.read_diff" => Some(AgentIsa::ReadDiff),
            "obs.read_test_results" => Some(AgentIsa::ReadTestResults),
            "obs.read_build_output" => Some(AgentIsa::ReadBuildOutput),
            "obs.read_dependencies" => Some(AgentIsa::ReadDependencies),
            "obs.read_call_graph" => Some(AgentIsa::ReadCallGraph),
            "obs.read_type_graph" => Some(AgentIsa::ReadTypeGraph),
            "obs.read_repo_map" => Some(AgentIsa::ReadRepoMap),
            "dec.classify_task" => Some(AgentIsa::ClassifyTask),
            "dec.classify_error" => Some(AgentIsa::ClassifyError),
            "dec.classify_file" => Some(AgentIsa::ClassifyFile),
            "dec.select_scope" => Some(AgentIsa::SelectScope),
            "dec.select_file" => Some(AgentIsa::SelectFile),
            "dec.select_symbol" => Some(AgentIsa::SelectSymbol),
            "dec.select_tool" => Some(AgentIsa::SelectTool),
            "dec.select_test" => Some(AgentIsa::SelectTest),
            "dec.select_strategy" => Some(AgentIsa::SelectStrategy),
            "dec.rank_candidates" => Some(AgentIsa::RankCandidates),
            "dec.assess_risk" => Some(AgentIsa::AssessRisk),
            "dec.assess_completeness" => Some(AgentIsa::AssessCompleteness),
            "dec.assess_confidence" => Some(AgentIsa::AssessConfidence),
            "dec.assess_regression_risk" => Some(AgentIsa::AssessRegressionRisk),
            "mut.create_file" => Some(AgentIsa::CreateFile),
            "mut.delete_file" => Some(AgentIsa::DeleteFile),
            "mut.move_file" => Some(AgentIsa::MoveFile),
            "mut.rename_file" => Some(AgentIsa::RenameFile),
            "mut.replace_range" => Some(AgentIsa::ReplaceRange),
            "mut.replace_symbol" => Some(AgentIsa::ReplaceSymbol),
            "mut.insert_node" => Some(AgentIsa::InsertNode),
            "mut.delete_node" => Some(AgentIsa::DeleteNode),
            "mut.rename_symbol" => Some(AgentIsa::RenameSymbol),
            "mut.apply_patch" => Some(AgentIsa::ApplyPatch),
            "mut.apply_codemod" => Some(AgentIsa::ApplyCodemod),
            "mut.update_dependency" => Some(AgentIsa::UpdateDependency),
            "mut.update_config" => Some(AgentIsa::UpdateConfig),
            "tool.run_command" => Some(AgentIsa::RunCommand),
            "tool.run_script" => Some(AgentIsa::RunScript),
            "tool.run_test" => Some(AgentIsa::RunTest),
            "tool.run_test_set" => Some(AgentIsa::RunTestSet),
            "tool.run_build" => Some(AgentIsa::RunBuild),
            "tool.run_linter" => Some(AgentIsa::RunLinter),
            "tool.run_formatter" => Some(AgentIsa::RunFormatter),
            "tool.run_typecheck" => Some(AgentIsa::RunTypecheck),
            "tool.run_benchmark" => Some(AgentIsa::RunBenchmark),
            "obs.vcs.status" => Some(AgentIsa::Status),
            "obs.vcs.diff" => Some(AgentIsa::Diff),
            "obs.vcs.blame" => Some(AgentIsa::Blame),
            "obs.vcs.log" => Some(AgentIsa::Log),
            "obs.vcs.show" => Some(AgentIsa::Show),
            "obs.vcs.branch_info" => Some(AgentIsa::BranchInfo),
            "mut.vcs.stage" => Some(AgentIsa::Stage),
            "mut.vcs.unstage" => Some(AgentIsa::Unstage),
            "mut.vcs.restore" => Some(AgentIsa::Restore),
            "ver.parse" => Some(AgentIsa::Parse),
            "ver.compile" => Some(AgentIsa::Compile),
            "ver.format_check" => Some(AgentIsa::FormatCheck),
            "ver.lint" => Some(AgentIsa::Lint),
            "ver.typecheck" => Some(AgentIsa::Typecheck),
            "ver.unit_test" => Some(AgentIsa::UnitTest),
            "ver.integration_test" => Some(AgentIsa::IntegrationTest),
            "ver.behavior_check" => Some(AgentIsa::BehaviorCheck),
            "ver.api_compat_check" => Some(AgentIsa::ApiCompatCheck),
            "ver.regression_check" => Some(AgentIsa::RegressionCheck),
            "ver.security_check" => Some(AgentIsa::SecurityCheck),
            "ver.diff_review" => Some(AgentIsa::DiffReview),
            "ver.requirement_check" => Some(AgentIsa::RequirementCheck),
            "ctl.branch" => Some(AgentIsa::Branch),
            "ctl.parallel" => Some(AgentIsa::Parallel),
            "ctl.join" => Some(AgentIsa::Join),
            "ctl.retry" => Some(AgentIsa::Retry),
            "ctl.rollback" => Some(AgentIsa::Rollback),
            "ctl.checkpoint" => Some(AgentIsa::Checkpoint),
            "ctl.request_evidence" => Some(AgentIsa::RequestEvidence),
            "ctl.escalate" => Some(AgentIsa::Escalate),
            "ctl.wait_for_dependency" => Some(AgentIsa::WaitForDependency),
            "ctl.finish" => Some(AgentIsa::Finish),
            "dec.classify_intent" => Some(AgentIsa::ClassifyIntent),
            "dec.classify_risk" => Some(AgentIsa::ClassifyRisk),
            "dec.classify_resource" => Some(AgentIsa::ClassifyResource),
            "dec.is_complete" => Some(AgentIsa::IsComplete),
            "dec.is_relevant" => Some(AgentIsa::IsRelevant),
            "dec.is_supported" => Some(AgentIsa::IsSupported),
            "dec.is_reversible" => Some(AgentIsa::IsReversible),
            "dec.is_duplicate" => Some(AgentIsa::IsDuplicate),
            "dec.is_regression" => Some(AgentIsa::IsRegression),
            "dec.risk_level" => Some(AgentIsa::RiskLevel),
            "dec.complexity_level" => Some(AgentIsa::ComplexityLevel),
            "dec.urgency" => Some(AgentIsa::Urgency),
            "dec.novelty" => Some(AgentIsa::Novelty),
            "dec.impact" => Some(AgentIsa::Impact),
            "dec.select_model" => Some(AgentIsa::SelectModel),
            "dec.select_branch" => Some(AgentIsa::SelectBranch),
            "dec.rank_documents" => Some(AgentIsa::RankDocuments),
            "dec.rank_files" => Some(AgentIsa::RankFiles),
            "dec.rank_symbols" => Some(AgentIsa::RankSymbols),
            "dec.rank_patches" => Some(AgentIsa::RankPatches),
            "dec.rank_plans" => Some(AgentIsa::RankPlans),
            "dec.select_relevant_context" => Some(AgentIsa::SelectRelevantContext),
            "dec.select_affected_tests" => Some(AgentIsa::SelectAffectedTests),
            "dec.select_changed_dependencies" => Some(AgentIsa::SelectChangedDependencies),
            "dec.expected_success" => Some(AgentIsa::ExpectedSuccess),
            "dec.expected_cost" => Some(AgentIsa::ExpectedCost),
            "dec.expected_latency" => Some(AgentIsa::ExpectedLatency),
            "dec.expected_information_gain" => Some(AgentIsa::ExpectedInformationGain),
            "ctl.continue" => Some(AgentIsa::Continue),
            "ctl.review" => Some(AgentIsa::Review),
            "ctl.block" => Some(AgentIsa::Block),
            "obs.parse_task_request" => Some(AgentIsa::ParseTaskRequest),
            "obs.extract_explicit_deliverables" => Some(AgentIsa::ExtractExplicitDeliverables),
            "obs.extract_hard_constraints" => Some(AgentIsa::ExtractHardConstraints),
            "dec.infer_acceptance_criteria" => Some(AgentIsa::InferAcceptanceCriteria),
            "dec.detect_ambiguity" => Some(AgentIsa::DetectAmbiguity),
            "dec.select_clarify_or_default" => Some(AgentIsa::SelectClarifyOrDefault),
            "state.initialize_task_state" => Some(AgentIsa::InitializeTaskState),
            "obs.fingerprint_environment" => Some(AgentIsa::FingerprintEnvironment),
            "obs.detect_project_roots" => Some(AgentIsa::DetectProjectRoots),
            "obs.detect_languages" => Some(AgentIsa::DetectLanguages),
            "obs.detect_build_system" => Some(AgentIsa::DetectBuildSystem),
            "state.activate_primitive_packs" => Some(AgentIsa::ActivatePrimitivePacks),
            "obs.build_repo_index" => Some(AgentIsa::BuildRepoIndex),
            "obs.build_symbol_graph" => Some(AgentIsa::BuildSymbolGraph),
            "obs.build_dependency_graph" => Some(AgentIsa::BuildDependencyGraph),
            "ctx.generate_search_intent" => Some(AgentIsa::GenerateSearchIntent),
            "ctx.retrieve_candidate_files" => Some(AgentIsa::RetrieveCandidateFiles),
            "ctx.retrieve_candidate_symbols" => Some(AgentIsa::RetrieveCandidateSymbols),
            "ctx.expand_structural_context" => Some(AgentIsa::ExpandStructuralContext),
            "dec.score_context_relevance" => Some(AgentIsa::ScoreContextRelevance),
            "ctx.compile_model_context" => Some(AgentIsa::CompileModelContext),
            "dec.select_workflow_template" => Some(AgentIsa::SelectWorkflowTemplate),
            "plan.instantiate_compute_graph" => Some(AgentIsa::InstantiateComputeGraph),
            "plan.propose_plan_branches" => Some(AgentIsa::ProposePlanBranches),
            "dec.score_plan_branch" => Some(AgentIsa::ScorePlanBranch),
            "plan.prune_branches" => Some(AgentIsa::PruneBranches),
            "plan.detect_information_gap" => Some(AgentIsa::DetectInformationGap),
            "dec.select_next_graph_node" => Some(AgentIsa::SelectNextGraphNode),
            "dec.assess_completion" => Some(AgentIsa::AssessCompletion),
            "dec.select_tool_family" => Some(AgentIsa::SelectToolFamily),
            "dec.select_tool_operation" => Some(AgentIsa::SelectToolOperation),
            "tool.resolve_argument_from_state" => Some(AgentIsa::ResolveArgumentFromState),
            "tool.generate_free_argument" => Some(AgentIsa::GenerateFreeArgument),
            "tool.validate_tool_schema" => Some(AgentIsa::ValidateToolSchema),
            "policy.authorize_tool_call" => Some(AgentIsa::AuthorizeToolCall),
            "tool.execute" => Some(AgentIsa::ExecuteTool),
            "dec.classify_tool_failure" => Some(AgentIsa::ClassifyToolFailure),
            "tool.recover" => Some(AgentIsa::SelectRecoveryAction),
            "mut.define_mutation_scope" => Some(AgentIsa::DefineMutationScope),
            "dec.select_edit_representation" => Some(AgentIsa::SelectEditRepresentation),
            "mut.generate_patch_candidate" => Some(AgentIsa::GeneratePatchCandidate),
            "mut.generate_test_candidate" => Some(AgentIsa::GenerateTestCandidate),
            "mut.apply_patch_transactionally" => Some(AgentIsa::ApplyPatchTransactionally),
            "mut.format_changed_code" => Some(AgentIsa::FormatChangedCode),
            "ctx.update_affected_context" => Some(AgentIsa::UpdateAffectedContext),
            "dec.compare_patch_candidates" => Some(AgentIsa::ComparePatchCandidates),
            "ver.parse_validate" => Some(AgentIsa::ParseValidate),
            "ver.typecheck_affected" => Some(AgentIsa::TypecheckAffected),
            "ver.run_target_tests" => Some(AgentIsa::RunTargetTests),
            "dec.classify_diagnostic" => Some(AgentIsa::ClassifyDiagnostic),
            "dec.localize_failure_cause" => Some(AgentIsa::LocalizeFailureCause),
            "dec.select_repair_strategy" => Some(AgentIsa::SelectRepairStrategy),
            "ctl.rollback_mutation" => Some(AgentIsa::RollbackMutation),
            "ver.verify_requirements" => Some(AgentIsa::VerifyRequirements),
            "ver.check_unresolved_failures" => Some(AgentIsa::CheckUnresolvedFailures),
            "ver.check_artifact_existence" => Some(AgentIsa::CheckArtifactExistence),
            "ver.check_acceptance_evidence" => Some(AgentIsa::CheckAcceptanceEvidence),
            "dec.decide_finish_continue_escalate" => Some(AgentIsa::DecideFinishContinueEscalate),
            "ctl.compose_final_report" => Some(AgentIsa::ComposeFinalReport),
            "state.persist_run_receipt" => Some(AgentIsa::PersistRunReceipt),
            "mem.update_long_term_memory" => Some(AgentIsa::UpdateLongTermMemory),
            "state.close_task_state" => Some(AgentIsa::CloseTaskState),
            "route.describe_cognitive_requirement" => Some(AgentIsa::DescribeCognitiveRequirement),
            "route.filter_eligible_models" => Some(AgentIsa::FilterEligibleModels),
            "route.predict_model_success" => Some(AgentIsa::PredictModelSuccess),
            "route.estimate_route_cost" => Some(AgentIsa::EstimateRouteCost),
            "route.select_logical_model" => Some(AgentIsa::SelectLogicalModel),
            "route.select_state_transfer_mode" => Some(AgentIsa::SelectStateTransferMode),
            "route.preload_model" => Some(AgentIsa::PreloadModel),
            "route.evict_model" => Some(AgentIsa::EvictModel),
            "state.validate_translated_state" => Some(AgentIsa::ValidateTranslatedState),
            "ctx.reconstruct_semantic_context" => Some(AgentIsa::ReconstructSemanticContext),
            _ => None,
        }
    }

    /// True for `mut.*` primitives (state-mutating; need write_set + authorization).
    pub fn is_mutation(self) -> bool {
        self.id().starts_with("mut.")
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::kernel::registry::PrimitiveRegistry;

    #[test]
    fn isa_matches_registry_exactly() {
        let r = PrimitiveRegistry::global();
        assert_eq!(AgentIsa::ALL.len(), 191);
        assert_eq!(AgentIsa::ALL.len(), r.len());
        for (isa, p) in AgentIsa::ALL.iter().zip(r.iter()) {
            assert_eq!(isa.id(), p.id, "order/id drift");
            assert_eq!(AgentIsa::from_id(&p.id), Some(*isa));
        }
        assert_eq!(AgentIsa::from_id("nope.x"), None);
    }

    #[test]
    fn mutation_flag() {
        assert!(AgentIsa::from_id("mut.apply_patch").unwrap().is_mutation());
        assert!(!AgentIsa::from_id("obs.list_files").unwrap().is_mutation());
    }
}
